List<String> chapter_11_trans_sanskrit = [
  "Arjuna uvācha: madanugrahāya paramam guhyam adhyātmasamjñitam yat tvayoktam vacas tena moho 'yam vigato mama",
  "bhavāpyayau hi bhūtānām śrutau vistaraśo mayā tvattah kamalapatrāksa māhātmyam api cāvyayam",
  "evam etad yathāttha tvam ātmānam parameśvara drastum icchāmi te rūpam aiśvaram purusottama",
  "manyase yadi tac chakyam mayā drastum iti prabho yogeśvara tato me tvam darśayātmānam avyayam",
  "śrī-bhagavān uvāca paśya me pārtha rūpāni śataśo'tha sahasraśah nānā-vidhāni divyāni nānā-varnākrtīni ca",
  "paśyādityān vasūn rudrān aśvinau marutastathā bahūni-adrsta-pūrvāni paśyāścaryāni bhārata",
  "ihai-kastham jagat krtsnaḿ paśyādya sakalācarām mama dehe gudākeśa yac cānyad drastum icchasi",
  "na tu māḿ śakyase drastum anenaiva svacaksusā divyaḿ dadāmi te caksuh pasyame yogam aiśvaram",
  "sañjaya uvāca evam uktvā tato rājan mahā-yogeśvaro harih darśayām āsa pārthāya paramaḿ rūpam aiśvaram",
  "aneka-vaktra-nayanam aneka-adbhuta-darshanam aneka-divya-abharanam divya-aneka-udyata-ayudham",
  "Divyam ālyāmbara-dharam divya-gandhānulepanam, Sarvāścaryamayam devam anantam viśvato-mukham",
  "divi sūryasahasrasya bhavedyugapadutthitā, yadi bhāh sadrśī sā syādbhāsastasya mahātmanah",
  "tatraikastham jagatkrtsnam pravibhaktamanekadhā, apaśyaddevadevasya śarīre pāndavastadā ",
  "Tatah sa vismayavishto hrishhtaroma dhananjayah, pranamya shirasa devam kritanjali rabhashata.",
  "Arjuna uvācha paśyāmi devāms tava deva dehe sarvāms tathā bhūta-viśhesha-sanghān brahmānam īśham kamalāsana-stham rishīmśh cha sarvān uragānśhcha divyān.",
  "Anekabāhūdaravaktranetram pashyāmi tvām sarvato’nantarūpam nāntam na madhyam na punastavādim pashyāmi viśveśvara viśvarūpa",
  "kirītinam gadinam cakrinam ca tejorāśim sarvato dīptimantam paśyāmi tvām durnirīksyam samantād dīptānalārkadyutimaprameyam",
  "tvam aksaram paramam veditavyam tvam asya viśvasya param nidhānam tvam avyayah śāśvatadharmagoptā sanātanastvam puruso mato me",
  "anādi-madhyāntam anantavīrya-mantabāhum śaśisūrya-netram paśyāmi tvām dīptahutāśa-vaktram svatejasā viśvam idam tapantam",
  "dyāvāprthivyōridamantarm hi vyāptam tvayaikena diśaśca sarvāh drstvādbhutam rūpamugram tavedam loktrayam pravyathitam mahātman",
  "Amii hi tvaam sura-sanghaa vishanti Kechid bhiitaah praannjalayo griinanti Svastiityuktva maharshi-siddha-sanghaah Stuvanti tvaam stutibhih pushkalaabhih",
  "Rudraadityaa vasavo ye cha saadhyaa Viswe'shwinou marutashcho'shmapaashcha  Gandharva-yakshaasura-siddha-sanghaa Veekshante tvaam vismitaashchaiva sarve",
  "Roopam mahatte bahu vaktra netram Mahabaho bahubahuuru paadam, Bahoodaram bahudamshtra karalam Drushtwaa lokah pravyathitaas tathaa'ham",
  "nabhaspr̥śam dīptamanekavarnam vyāttānanam dīptaviśālanetram, drstvā hi tvām pravyathitāntarātmā dhrtim na vindāmi śamam cha visno",
  "damstrākarālāni ca te mukhāni drstvaiva kālānalasannibhāni, diśo na jāne na labhe ca śarma prasīda deveśa jagannivāsa",
  "amī ca tvām dhrtarāstrasya putrāh sarve sahaivāvanipālasanghaih, bhīsmo dronah sūtaputrastathāsau sahāsmadīyairapi yodhamukhyaih ",
  "vaktraaNi te tvaramaaNaa vishanti damshTraakaraalaani bhayaanakaani, kechid vilagnaa dashanaantareshu sandR^ishyante chuurNitairutamaaN^gaiH",
  "yathā nadīnām bahavo'mbuvegāh samudramevābhimukhā dravanti, tathā tavāmī naralokavīrā viśanti vaktrānyabhivijvalanti",
  "yathā pradīptam jvalanam patan̄gā viśanti nāśāya samrddhavegāh, tathaiva nāśāya viśanti lokāh tavāpi vaktrāni samrddhavegāh",
  "lelihyase grasamānah samantāl- lokān samagrān vadanair jvaladbhih, tejobhir āpūrya jagat samagram bhāsas tavo'grāh pratapanti visno",
  "aakhyaahi me ko bhavaanugrahaarupo namo.astu te devavara praseeda vijnaatumicchaami bhavantamaadyam na hi prajaanaami tava pravrittima.",
  "śrībhagavānuvāca, kālo'smi lokaksayakrtpravrddho lokānsamāhartumiha pravrttah, rte'pi tvām na bhavisyanti sarve ye'vasthitāh praty-anīkesu yodhāh",
  "Tasmāttvamuttishtha yasho labhasva Jitvā śatrūn bhuńksva rājyam samrddham Mayaivaitē nihatāh pūrvamēva Nimittamātram bhava savyasācin.",
  "Dronam cha Bhishmam cha Jayadratham cha, Karnam tathanyanapi yodhaviran, Mayaa hataamstwam jahi ma vyathishthaa, Yudhyaswa jetasi rane sapatnaan.",
  "Sanjaya uvacha, Etacchrutva vachanam keshavasya, Kritanjalirvepamaanah kiriti, Namaskritwa bhooya evaha krishnam, Sagadgadam bheetabheetah pranamya.",
  "arjuna uvāca sthāne hrsīkeśa tava prakīrtyā jagat prahrsyatyanurajyate ca raksāmsi bhītāni diśo dravanti sarve namasyanti ca siddha-sanghāh",
  "kasmāt cha te na nameran mahātman garīyase brahmano'py ādi-kartre ananta deveśa jagannivāsa tvam aksaram sad-asat tat param yat",
  "tva-mādidevah purusah purānas tva-masya viśvasya param nidhānam vettāsi vedyam ca param ca dhāma tvayā tataḿ viśvam anantarūpa",
  "vāyu r yamo'gnir varunah śaśānkah prajāpati stvam prapitāmahaśca, namo namaste'stu sahasrakrtvah punaśca bhūyo'pi namo namaste",
  "namah purastād atha prstha-tas te namo 'stu te sarvata eva sarva ananta-vīryāmita-vikrama-stvaḿ sarvam samāpnosi tato 'si sarvah",
  "sakheti matvā prasabham yad uktam he krsna he yādava he sakheti ajānatā mahimānam tavedam mayā pramādāt pranayena vāpi",
  "yachchavahāsārtham asatkrto'si vihāraśhayyāsana-bhojaneshu eko'thavāpyachyuta tatsamaksham tatkshāmaye tvām aham aprameyam",
  "Pitāsi lokasya carācasya tvamasya pūjyaśca gururgarīyān na tvatsamo'styabhyadhikah kuto'nyo lokatraye'pyapratimaprabhāva",
  "Tasmāt pranamya pranidhāya kāyam prasādaye tvām aham īśam īdyam piteva putrasya sakheva sakhyuh priyah priyāyārhasi deva sodhum.",
  "Adrsta-pūrvam hrsitō'smi drstvā bhayēna cha pravyathitam manō mē tadēva mē darśaya dēva rūpam prasīda dēvēśa jagannivāsa.",
  "Kirītinam gadinam chakrahastam icchāmi tvām drstum aham tathaiva tenaiva rūpena caturbhujena sahasrabāho bhava viśvamūrte.",
  "Śrī Bhagavān uvācha: Mayā prasannena tavārjunedam Rūpam param darśitam ātma-yogāt Tejomayam viśvam anantam ādyam Yanme tvadanyena na drsta-pūrvam.",
  "na vedayajña-adhyayanair na dānair na ca kriyābhir na tapobhir ugraih evam-rūpah śakya aham nr-loke drastum tvadanyena kurupravīra",
  "mā te vyathā mā ca vimūdhabhāvo drstvā rūpam ghoram idrinmamedam vyapetabhīh prītamanāh punastvam tadeva me rūpamidam prapaśya",
  "Sanjaya uvacha: Iti arjunam vasudevastathoktva Svakam rupam darshayamasabhuyah Ashvasayamasa cha bhitamenam Bhutva punah saumyavapurmahatma.",
  "Arjuna uvāca drstvemam mānusam rūpam tava saumyam janārdana idānīmasmi samvrttah sacetāh prakrtim gatah",
  "śrī bhagavān uvāca sudurdarśam idam rūpam drstavān asi yan mama devā apy asya rūpasya nityam darśana-kānksinah",
  "naaham vedair na tapasaa na daanena na chejyayaa shakya evam-vidho drashtum drishtavaanasi maam yathaa",
  " Bhaktyā tvananyayā śakya aham evam-vidho 'rjuna, jñātum drashtum ca tattvena praveshtum ca parantapa.",
   "matkarma-krn matparamo madbhaktah sangavarjitah nirvairah sarvabhūtesu yah sa mām eti pāndava",
];


List<String> chapter_11_english = [
  "Arjuna said: For the benefit of me, please reveal the supreme, secret knowledge of the self. With those words spoken by you, this delusion of mine has been dispelled.",
  "The cycle of birth and death of all beings has its origin in me. This is revealed in the scriptures in great detail. You are also indestructible, O lotus-eyed one, and your glories are limitless.",
  "O Supreme Lord, as You have described Yourself, I wish to see You in that form. O best of persons, if You think that I am able to behold Your cosmic form, then kindly show me that unlimited, supreme, divine form.",
  "O Lord of yoga, if You think that I am capable of seeing it, then please show me Your imperishable self.",
  "The Supreme Lord said: Behold, O Arjuna, My forms by the hundreds and thousands, in many different divine varieties, of various colors, shapes, and sizes.",
  "Behold, O Arjuna, the Adityas, the Vasus, the Rudras, the Asvins, and the Maruts. Behold many wondrous things never before seen, O Arjuna.",
  "Behold now, O Arjuna, the entire universe, with everything moving and stationary, situated in one place within my body. But you cannot see Me with your physical eyes; therefore, I give you divine eyes, so that you may behold my majestic opulence.",
  "But you cannot see Me with your ordinary eyes. Therefore, I give you divine eyes to see my majestic power and glory.",
  "Sanjaya said: O King, having spoken thus, the great Lord of Yoga, Hari (Krishna), showed Arjuna His universal form as the supreme, majestic, and divine.",
  "Many mouths and eyes had He, manifold were His wonderful sights, Many divine ornaments decked Him, and divine weapons shone bright.",
  "His divine form adorned with divine garlands and clothing, He wears divine fragrances and is resplendent with every kind of wonder. He is the infinite divine being, the beginning, middle, and end of everything, With faces on all sides, He is omnipresent and all-pervading.",
  "If a thousand suns were to rise in the sky simultaneously, their radiance might resemble the effulgence of the Supreme Person in that universal form.",
  "There he saw the entire universe divided in many ways, in the body of the God of gods, Pandava, at that time",
  "Then, filled with wonder and with hairs standing on end, Arjuna bowed his head to the Lord and spoke with folded hands:",
  "Arjuna said, \"I behold all the gods in Your body, O Lord, as also hosts of diverse classes of beings. Brahma the Creator, seated on his lotus-seat, and all the Rishis and divine serpents, I see in You.\"",
  "I see You with countless arms, stomachs, faces, and eyes. You are present everywhere and have infinite forms. I see no beginning, middle, or end to Your being. O Lord of the universe, I see You as the embodiment of everything.",
  "I see you with a crown, mace, discus, radiance, and blazing light from all sides. I see you like an immeasurable, dazzling fire and sun, difficult to look at from all directions.",
  "You are the imperishable, supreme, and should be known. You are the ultimate support of this universe. You are unchanging, eternal, the protector of dharma. To me, you are the eternal Person, this is my belief.",
  "You are without beginning, middle or end, of infinite power, with arms extending everywhere, and eyes as bright as the sun and moon. I see you, with your mouth aglow with the flames of sacrifice,burning this entire universe with your own radiance.",
  "O great soul! You alone pervade the expanse between heaven and earth, and all directions are encompassed by you. Beholding your wondrous and fierce form,the three worlds tremble in agitation.",
  "Some in the assemblage of celestial beings bow to You, while others extol You in fear. The company of sages and perfected beings proclaims \"All is well!\" and offers praise in various hymns.",
  "The Rudras, Adityas, Vasus, Sadhyas, Visvadevas, the two Asvins, the Maruts, and the Usmapas, and hosts of Gandharvas, Yakshas, Asuras, and Siddhas, all gaze at You in wonder.",
  "Your form is great, with many faces and eyes, Oh mighty-armed one, with many arms, thighs, feet, bellies, and fearful teeth; the worlds are frightened on seeing you like this, so am I.",
  "Your form is difficult to see because of its glaring effulgence, spreading on all sides like blazing fire or the immeasurable radiance of the sun. Yet I see this glowing form everywhere, adorned with various crowns, clubs, and discs, O Vishnu.",
   "Seeing your fearsome teeth and terrifying mouth resembling the fire of time, I do not know the directions nor do I find any solace. O Devesha, O Jagannivasa, be pleased and have mercy on me.",
  "All these sons of Dhritarashtra, along with their allied kings and Bhisma, Drona and Karna, and all our soldiers, are rushing into Your fearful mouths. And some I see trapped with heads smashed between Your teeth.",
  "Your fearful teeth and faces, looking so terrible, are scaring me. The sons of Dhritarashtra and all the kings present here with their armies are looking at You in fear. Even some of the great sages are bewildered when they see Your mouths with their fearful teeth and faces. O Lord of the universe, please be merciful to me. I cannot withstand the sight of Your fearful and gigantic form.",
  "Just as many streams of water rush towards the ocean, similarly these heroes of the human world enter into your blazing mouths.",
  "Just as moths rush to a blazing flame with great speed to meet their destruction, in the same way, the people's faces enter your burning and shining mouths with great speed for their destruction.",
  "You, who lick (devour) all the worlds, with your flaming mouths, you who fill the entire universe with your radiant energy, your terrible and bright rays burn forth, O Vishnu.",
  "Tell me who you are, O fierce form. Salutations to you, O supreme Lord. Have mercy on me. I desire to know you, the original Being. I do not understand your deeds.",
  "The Supreme Personality of Godhead said: Time I am, destroyer of the worlds, and I have come to engage all people. With the exception of you [the Pandavas], all the soldiers here on both sides will be slain.",
  "Therefore, arise and obtain glory. Conquer your enemies and enjoy prosperous kingdom. They are already slain by me, you are only an instrument of the battle, O Arjuna, the skilled archer.",
  "Therefore, strike down Drona, Bhishma, Jayadratha, Karna, and other brave warriors who are already slain by Me. Do not be disturbed by the illusion that you are the killer. Fight and you will conquer your enemies on the battlefield.",
  "Sanjaya said, Hearing these words of Keshava, the crown-wearing Arjuna, with joined palms, trembling, offered obeisance again and again, with a choked voice, and in fear.",
  "Arjuna said: O Hrishikesha, by praising You, the world rejoices and is filled with joy. All the directions, O Lord, fearfully run away, and the perfected ones bow down to You. ",
  "Why should they not offer their reverence to you, O Great One, who are greater even than Brahman, the primal cause? O limitless One, God of gods, abode of the universe, you are the imperishable, the Absolute Truth, which is both being and non-being.",
  "You are the primal God, the ancient being, the ultimate refuge of this universe. You are the knower, the knowable, and the supreme abode. By You, the universe is pervaded, O infinite form!",
  "Salutations to Vayu, Yama, Agni, Varuna, Chandra (the moon), Prajapati (the creator), and to Pitamaha (the great-grandfather). Salutations to you a thousand times, and again and yet again, salutations to you.",
  "Salutations to You in front and behind, O Supreme Being! Salutations to You on all sides, O All! O Infinite in Your power and prowess, You pervade all, and therefore You are everything.",
  "Thinking of You as my friend, I have rashly addressed You 'O Krishna,' 'O Yadava,' 'O my friend,' not knowing Your glories. Please forgive whatever I may have done in madness or in love. I have dishonored You many times, jesting as we relaxed, lay on the same bed, or sat or ate together, sometimes alone and sometimes in front of many friends. O infallible one, please excuse me for all those offenses.",
  "Whatever disrespect has been shown to You by me through ignorance, while playing, sitting, or eating, alone or in the presence of others, please forgive me for all that, O Achyuta, who is immeasurable.",
  "You are the father of this universe, the mother, the supporter, and the grandsire. You are the object of worship, the supreme guru, and the greatest benefactor. No one is equal to You, nor can anyone be greater than You. In the three worlds, there is no one who can attain a position superior to Yours.",
  "Therefore, surrendering all your body, mind, and words unto Me, and being completely absorbed in Me, please perform your duty for Me. Being completely dependent on Me, and taking refuge in Me, simply offer respects and obeisances unto Me. In this way, you will come to Me without fail. This is My promise to you, because you are My very dear friend.",
  "I am delighted by seeing what I have never seen before, but my mind is disturbed with fear. O Lord of lords, O refuge of the universe, please reveal to me Your divine form and kindly bless me with Your grace. I wish to see You as the supreme destroyer, O Lord.",
  "O Lord of the universe, I wish to see You in Your form as the crowned one, bearing a mace, discus, and conch. Please reveal Yourself to me in that four-armed form as the embodiment of the universe.",
  "The Blessed Lord said: My dear Arjuna, by My grace, I have shown you this supreme form which is effulgent, universal, and unlimited, and which has not been seen before by anyone other than yourself.",
  "Not by reciting the Vedas, nor by acts of charity, nor by performing rituals, nor by severe austerities can I be seen in the same way that you have been seen, O Arjuna. But by undivided devotion alone can I be known and seen in this form, O Arjuna, and can be truly understood and entered into.",
  "Do not be perturbed or bewildered by seeing this terrible form of mine. With a composed and fearless mind, behold this form again and become rejoiced.",
  "Sanjaya said: Having spoken thus to Arjuna, Krishna showed him His divine form once again. Reassuring him, Krishna, the great Lord, assumed His gentle human form again.",
  "Arjuna said: O Janardana, seeing this human-like form of Yours, so gentle, I am now composed in mind and restored to my original nature.",
  "The Supreme Lord said: My dear Arjuna, the form which you are now seeing is very difficult to behold. Even the demigods are ever desirous of seeing this form of mine.",
  "I am not able to see you in spite of studying the Vedas, performing austerities, giving charity or worshiping you with great devotion, as you have now revealed yourself to me in this way.",
  "My dear Arjuna, only by undivided devotional service can I be understood as I am, standing before you, and can thus be seen directly. Only in this way can you enter into the mysteries of My understanding.",
  "One who performs his duty without attachment, surrendering the results unto Me, and who is not influenced by violence, is a perfect devotee of Mine. He is not disturbed by anything, and he sees Me everywhere and in everyone.",
];