List<String> chapter_eight_trans_sanskrit = [
  "arjuna uvācha kim tad brahma kim adhyātmam kim karma purusottama adhibhūtam cha kim proktam adhidaivam kim uchyate",
  "adhiyajñah katham ko'tra dehe'smin madhusūdana prayāna-kāle cha katham jñeyo'si niyatātmabhih",
  "śrī-bhagavān uvāca aksaram brahma paramam svabhāvo'dhyātmamucyate bhūta-bhāvodbhava-karo visargah karmasamjñitah",
  "adhibhūtam ksaro bhāvah purusaścādhidaivatam adhiyajño'ham evātra dehe dehabhrtām vara",
  "Antakāle ca mām eva smaran muktvā kalevaram Yah prayāti sa madbhāvam yāti nāstyatra samśayah.",
  "Yam yam vāpi smaranbhāvam tyajatyante kalevaram tam tamevaiti kaunteya sadā tad-bhāva-bhāvitah",
  "Tasmāt sarvesu kālesu māmanusmara yudhya ca rāga-dvesa-vimuktais tu visayān indriyaiś caran",
  "Abhyāsa-yoga-yuktena cetasā nānya-gāminā Paramam purusam divyam yāti pārtha anucintayan",
  "Kavim purānam anuśāsitāram anor anīyāmsam anusmared yah sarvasya dhātāram acintya-rūpam āditya-varnam tamasah parastāt",
  "Prayāna-kāle manasāchalena bhakti-yogena yah sevate sa guhyam yoga-bhrasto ’bhijāyate tatra samsāyāvasto ’pi panditah",
"Yadaksharam vedavido vadanti Vishanti yadyatayo veetaraagaah Yadichchhanto brahmacharyam charanti Tatte padam sangrahena pravakshye.",
  "sarva-dvārāni samyamya mano hrdi nirudhya ca mūrdhny ādhāyātmanah prānam āsthito yoga-dhāranām",
  "omityekāksaram brahma vyāharanmāmanusmaran yah prayāti tyajandeham sa yāti paramām gatim",
  "ananyacetah satatam yo mām smarati nityaśah tasyāham sulabhah pārtha nitya-yuktasya yoginah",
  "Mamupetya punarjanma duhkhalayamashashvatam Napnuvanti mahatmanah samsiddhim paramam gatah",
  "Abrahmabhuvanallokaah punaraavartino'rjuna Maamupetya tu kaunteya punarjanma na vidyate",
  "Sahasrayugaparyantamaharyad brahmano viduhu Ratrim yugasahasrantam te'horatravido janah",
  "avyaktād vyaktayah sarvāh prabhavantyaharāgame rātryāgame pralīyante tatraivāvyakta-samjñake",
  "Bhutagramah sa evayam bhutva bhutva praliyate, Ratryagame'vashah partha prabhavatyaharagame.",
  "Parastasmaat tu bhaavo'nyo'vyakto'vyaktaat sanaatanah Yah sa sarveshu bhooteshu nashyatsu na vinashyati.",
  "avyakto'kshara ityuktah tamāhuh paramām gatim yam prāpya na nivartante tad dhāma paramam mama",
   "purushah sa parah partha bhaktya labhyas tvananyaya yasyantahsthani bhutani yena sarvamidam tatam",
  "Yatra kale twanavrittimavrittim chaiva yoginah, prayata yanti tam kalam vakshyami bharatarshabha.",
  "Agnir jyotir ahah śuklah sanmāsā uttarāyanam, tatra prayātā gacchanti brahma brahma-vido janāh.",
  "Dhumo ratristathā krsnah sanmāsā daksināyanam, Tatra cāndramasam jyotir yogī prāpya nivartate",
  "Shuklakrsne gatī hyete jagatah śāśvate mate, Ekayā yātyanāvrttim anyayāvartate punah",
  "Naite srtī pārtha jānanyogī muhyati kaścana, Tasmātsarvesu kālesu yogayukto bhavārjuna",
  "Vedesu yajñesu tapahsu caiva Dānesu yatpunyaphalam pradistam, Atyeti tatsarvamidam viditvā, Yogī param sthānamupaiti cādyam.",
  ];


List<String> chapter_eight_english = [
"Arjuna said: O Supreme Person, what is Brahman? What is the self? What are fruitive activities? What is this material manifestation? And what are the demigods? Please explain this to me.",
  "Arjuna asked, \"O Madhusudana, who is the Adhibhuta and how does he dwell in this body? How can you be realized at the time of death by those who have fixed their minds on you?\"",
  "The Supreme Lord said: The imperishable Brahman is the highest reality and is called the Self. Its essential nature is called adhyatma. The creation of the material world is called bhutabhava, while the dissolution of the material world is called visarga, and action in the material world is called karma.",
  "I am the Adhibhuta (the Lord of the material elements), the perishable manifestation of the spirit, and the Adhidaiva (the Lord of the celestial gods), the imperishable manifestation. I alone am the Adhiyajna (the Lord of all sacrifices) present in this body, O best among those who uphold righteousness.",
  "And whoever, at the end of their life, quits their body remembering me alone, at once attains my nature. Of this there is no doubt.",
  "Whatever state of being one remembers when one quits their body, O son of Kunti (Arjuna), one attains that state without fail as one's nature is molded by their thoughts and beliefs.",
  "Therefore, always remember Me and also do your duty of fighting the battle. With mind and senses disciplined by renunciation, and freed from the dualities of attraction and aversion, be always absorbed in Me.",
  "O Partha, one who, with a mind undistracted by any other practice, constantly engages in the practice of meditation upon the Supreme Person, attains the divine and transcendental destination.",
  "Whoever, at the time of death, with a mind steadfast and absorbed in the thought of the Supreme Lord, and with the power of yoga, fixes the life air between the eyebrows, he reaches the highest divine person.",
  "Whoever, at the time of death, with a mind fixed in devotion, and with the strength of yoga, holds the life breath steadily between the eyebrows, and then, by the power of devotion, focuses the mind entirely on the Supreme Lord, will certainly attain to Him.",
  "What is that imperishable word which the knowers of the Vedas declare, and by which the renunciants cross over the fear of death? What is that desire which, O Nachiketas, leads men to practice brahmacharya (celibacy) and austerity? That goal I tell thee briefly: it is Om.",
  "The yogi should hold the mind steady, restraining it from all sides, and fixing it on the heart. He should then steadily draw the life-breath into the Self, and with the mind absorbed in the Self, he should hold it there.",
  "One who departs from the body while remembering Me, the Supreme Personality of Godhead, and chanting the syllable Om, will attain the supreme goal.",
  "For those who always remember Me without deviation, I am easily attainable, O Partha, because they are always absorbed in the yoga of devotion.",
  "Those who reach Me are not reborn in this impermanent and painful world, they achieve the highest perfection.",
  "From the highest planet in the material world down to the lowest, all are places of misery wherein repeated birth and death take place. But one who attains to My abode, O son of Kunti, never takes birth again.",
  "By human calculation, a thousand ages taken together form the duration of Brahma's one day. And such also is the duration of his night. Those who know this reality of day and night of Brahma attain eternal life, and are not reborn at the dawn of Brahma's day or the beginning of his night.",
  "All beings, O Arjuna, are unmanifest in their beginning, manifest in their interim state, and unmanifest again in their end. So what need is there for lamentation?",
  "Everything in this world is born and perishes, as per the Vedantic concept of expansion, structure, and destruction.",
  "Never was there a time when I did not exist, nor you, nor all these kings; nor in the future shall any of us cease to be.",
  "That which is known as the unmanifest and the imperishable, they say, is the highest goal. Those who reach it never return. That is my highest abode.",
  "O Partha, that supreme person is reached by unalloyed devotion unto Him alone, and by no other means. To those who constantly meditate upon Him within the self, the Supreme Lord is very near; but to the impure, He appears to be far away.",
  "O best of the Bharatas, I shall now explain to you the times which, if departed from, do not return, those which return, and those which are both return and non-return.",
  "Those who know the Supreme Brahman attain that Supreme by passing away from the world during the influence of the fiery god, in the light, at an auspicious moment of the day, during the fortnight of the waxing moon, or during the six months when the sun travels in the north.",
  "The smoke-like darkness of night, the southern solstice of the sun, and the bright moon of the lunar month, the yogi who reaches it, is liberated.",
  "This verse from the Bhagavad Gita describes the two paths that lead to liberation. The path of light (shukla) leads to eternal happiness and the path of darkness (krishna) leads to rebirth. The cycle of birth and death can only be broken by those who follow the path of light, while those who follow the path of darkness continue to be trapped in the cycle of samsara.",
  "This verse emphasizes the importance of consistent and devoted practice of yoga for achieving inner peace and spiritual liberation.",
  "Having understood that the results of virtuous deeds such as Vedic rituals, sacrifices, austerities, and charitable acts are all limited, the yogi transcends them and reaches the supreme eternal abode.",
];