List<String> chapter_ten_trans_sanskrit = [
  "śrībhagavān uvāca, bhūya eva mahābāho śrnu me paramam vacah, yat te 'ham prīyamānāya vaksyāmi hitakāmyayā ॥",
  "na me viduh suraganāh prabhavam na maharsayah ahamādir hi devānām maharsīnām ca sarvaśah",
  "yo māmajam anādim ca vetti lokamaheshvaram asammūdhah sa martyesu sarvapāpaih pramucyate",
  "buddhir jnana masammohah kshama satyam damah shamah sukham duhkham bhavo 'bhavo bhayam cabhayam eva ca",
  "ahimsā samatā tustis tapo dānam yaśo'yaśah bhavanti bhāvā bhūtānām matta eva prthag-vidhāh",
  "maharsayah saptapūrve caturāro manavastathā madbhāvā mānasā jātā yesām loka imāh prajāh",
  "etām vibhūtim yogam ca mama yo vetti tattvatah so'vikampena yogena yujyate nātra samśayah",
  "aham sarvasya prabhavo mattah sarvam pravartate iti matva bhajante mam budha bhava-samanvitah",
  "Machchittā mad-gata-prānā bodhayantah parasparam Kathayantaśca mām nityam tushyanti ca ramanti ca",
  "Tesām satata-yuktānām bhajatām prīti-pūrvakam Dadāmi buddhi-yogam tam yena mām upayānti te.",
  "Teshām evānukampārtham aham ajñāna-jam tamah nāśayāmy ātma-bhāva-stho jñāna-dīpena bhāsvatā",
  "arjuna uvāca param brahma param dhāma pavitram paramam bhavān purusam śāśvatam divyam ādi-devam ajam vibhum",
  "āhus tvām rsayah sarve devarsir nāradastathā asito devalo vyāsah svayam caiva bravīsi me",
  "sarvam etad ritam manye yan mam vadasi keshava na hi te bhagavan vyaktim vidur deva na danavah",
  "Svayamevaatmanaatmaanam vetha twam purushottama Bhootabhaavana bhootesha devadeva jagatpate",
  "vaktum arhasyaśesena divyā hyātmavibhūtayah yābhir vibhūtibhir lokān imāms tvam vyāpya tishthasi",
  "Katham vidyām aham yogims tvam sadā paricintayan Kesu kesu ca bhāvesu cintyo'si bhagavan mayā.",
  "Vistarenātmano yogam vibhūtim ca janārdana Bhūyah kathaya trptir hi śrnvato nāsti me'mrtam.",
  "Shri Bhagavan uvacha, hanta te kathayishyami divya hyatmavibhutayah, pradhanyatah kurushreshtha nastyanto vistarasyme.",
  "Aham atma gudakesha sarva-bhutashaya-sthitah, aham adishcha madhyam cha bhutanam anta eva cha.",
  "Adityanamaham vishnur jyotisham raviramshuman, marichir marutam asmi nakshatranamaham shashi.",
  "Vedanam samavedo'smi devanamasmi vasavah, indriyanam manashchasm bhutanam asmi chetana.",
  "Rudranam shankarashchasmi vitthesho yaksharakshasam, vasunam pavakashchasmi meruh shikharinamaham.",
  "Purodhasam cha mukhyam mam viddhi Partha Brihaspatim, senaninam aham Skandah sarasam asmi sagarah.",
  "Maharshinām bhrguraham girāmasmyekamaksaram, Yajñānām japayajño'smi sthāvarānām himālayah",
  "Aśvatthah sarvavrksānām devarsīnām cha nāradah, Gandharvānām chitrarathah siddhānām kapilo munih",
  "Uccaihśravasam-aśvānām viddhi mām amrtodbhavam, Airāvatam gajendrānām narānām cha narādhipam",
  "Āyudhānām-aham vajram dhenuunām-asmi kāmadhuk, Prajanaś-chāsmi kandarpah sarpānām-asmi vāsukih",
  "Anantaś-chāsmi nāgānām varuno yādasām-aham, Pitṝnām-aryamā chāsmi yamah samyamatām-aham",
  "Prahlādaś-chāsmi daityānām kālah kalayatām-aham, Mrgānām cha mrgendro-aham vainateyaś-cha paksinām",
  "Pavanah pavatām-asmi Rāmah śastrabhrtām-aham, Jhashānām makaraś-chāsmi srotasām-asmi jāhnavī",
  "Sargānām ādir-antaś cha madhyam chaivāham arjuna, Adhyātma-vidyā vidyānām vādah pravadatām aham",
  "aksarānāmakāro'smi dvandvah sāmāsikasya ca ahamevāksayah kālo dhātāhaḿ viśvatomukhah",
  "mrtyuh sarvaharaś cāham udbhavaś ca bhavisyatām, kīrtih śrīrvāk ca nārīnām smrtir medhā dhrtih ksamā",
  "brhatsāma tathā sāmnām gāyatrī chandhasāmaham māsānām mārgaśīrso'hamrtūnām kusumākarah",
  "dyūtam chalayatāmasmi tejas tejasvinām aham jayo’smi vyavasāyo’smi sattvam sattvavatām aham",
  "vrsnīnām vāsudevō'smi pāndavānām dhanañjayah, munīnāmapyaham vyāsah kavīnāmuśanā kavih",
  "Dando damayatām asmi nītirasmi jigīsatām, Maunam caivāsmi guhyānām jñānam jñānavatām aham",
  "yacchāpi sarvabhūtānām bījam tadahamarjuna na tadasti vinā yatsyānmayā bhūtam carācaram",
  "Na anto'sti mama divyaanaam vibhootiinaam parantapa; esha tuuddeshatah prokto vibhuutervistaro maya.",
  "yadyad vibhūtimat sattvam śrīmadoorjitameva vā tattadevāvagaccha tvam mama tejo-'śasambhavam",
  "athavā bahunaitena kim jñātena tavārjuna vistabhyāhamidam krtsnam ekāmśena sthito jagat",
  ];



List<String> chapter_ten_english = [
  "Śrī Bhagavān said: Again, O mighty-armed Arjuna, listen to My supreme word, which I shall speak to you who are dear to Me for your benefit.",
  "The demigods do not know my origin, nor do the great sages. I am the source of all demigods and sages.",
  "He who knows Me as the unborn, as the beginningless, as the Supreme Lord of all the worlds—he, undeluded among men, is freed from all sins.",
  "Buddhi (intellect), jnana (knowledge), asammoha (clarity), kshama (forgiveness), satya (truth), dama (self-control), shama (mental peace), sukha (happiness), dukha (distress), bhava (birth), abhava (death), bhaya (fear), and abhaya (fearlessness) - all these are nothing but the Supreme Being.",
  "Non-violence, equanimity, contentment, penance, charity, fame and infamy, these states of being of creatures arise from Me alone, separately.",
  "Seven great sages and four Manus, as well as their mental creations, have sprung from My mind, and all the creatures in these planets descend from them.",
  "Whoever understands in truth this my glory and yoga, becomes united with it unshakenly by means of unwavering yoga; there is no doubt about it.",
  "I am the source of all, from Me everything originates. The wise who know this worship Me with loving devotion.",
  "With their minds focused on me and their lives surrendered to me, enlightening one another and talking about me constantly, they are contented and delighted.",
  "To those who are constantly devoted and worship Me with love, I give the understanding by which they can come to Me.",
  "To show them special mercy, I, dwelling in their hearts, destroy with the shining lamp of knowledge the darkness born of ignorance.",
  "Arjuna said: \"You are the Supreme Brahman, the ultimate, the supreme abode and purifier, the Absolute Truth and the eternal divine person. You are the primal God, transcendental and original, and You are the unborn and all-pervading beauty.\"",
  "The sages, along with the divine sage Narada, Asita, Devala, and Vyasadeva, all proclaim this of You. And now You Yourself are declaring it to me.",
  "O Keshava, I believe that all that You have said to me is true. O Lord, neither the gods nor the demons comprehend Your manifestations.",
  "You, O Supreme Person, know Yourself by Yourself. You are the Lord of all creatures, the Creator of all, the God of gods, the Supreme controller of the universe.",
  "Please describe in detail Your divine glories, by which You pervade all these worlds by Your manifestations. O Lord, by expanding Your transdental form, You always reside in them.",
  "How should I know you, O Yogi, ever steadfast in concentration? In what aspects and forms are you to be meditated on, O blessed Lord?",
  "Tell me again in detail, O Janardana (Krishna), of Your mighty powers and glories, for I never tire of hearing Your nectar-like words.",
  "Shri Bhagavan said, \"O Kurusreshta (best among the Kurus)! I shall now tell you about the divine manifestations of the Self. However, there is no end to the extent of my greatness, and therefore, I shall only speak briefly.\"",
  "Lord Krishna said, \"O Arjuna, I am the Self, situated within all beings. I am the beginning, the middle, and also the end of all beings.\"",
  "Lord Krishna said, \"Among the Adityas, I am Vishnu; among the luminaries, I am the radiant sun. Among the Maruts, I am Marichi, and among the stars, I am the moon.\"",
  "Lord Krishna said, \"Among the Vedas, I am the Sama Veda; among the gods, I am Indra. Among the senses, I am the mind, and among living beings, I am consciousness.\"",
  "Lord Krishna said, \"Among the Rudras, I am Shankara; among the Yakshas and Rakshasas, I am the lord of wealth. Among the Vasus, I am the fire god, and among the mountains, I am Meru.\"",
  "Lord Krishna said, \"Know me to be the chief among priests, O Arjuna, and among the commanders of armies, I am Skanda. Among bodies of water, I am the ocean.\"",
  "Of the great sages I am Bhrgu; of vibrations I am the transcendental om. Of sacrifices I am the chanting of the holy names [japa], and of immovable things I am the Himalayas.",
  "Of all trees I am the banyan tree; of the sages among the demigods I am Nārada. Of the celestial musicians I am Citraratha, and among the perfected beings I am the sage Kapila.",
  "Among horses know me to be Uccaihśravas, born of the nectar ocean. Of lordly elephants I am Airāvata, and among men I am the monarch.",
  "Of weapons I am the thunderbolt; among cows I am the surabhi. Of procreators I am Kandarpa, the god of love, and of serpents I am Vāsuki, the chief.",
  "Of the many hooded Nagas, I am Ananta. Among the aquatic beings I am Varuna, and of the manes I am Aryama. Among subduers I am Yama, the lord of death.",
  "Of demons I am Prahlada, and of reckoners of time I am Time himself. Of beasts I am the lion, and of birds I am Garuda, the son of Vinata.",
  "Of the purifiers, I am the wind, and of the wielders of weapons, I am Rama. Of fishes, I am the shark, and of flowing rivers, I am the Ganges.",
  "Of creations, I am the beginning, end, and middle, O Arjuna. Of all sciences, I am the science of the self, and of all debates, I am the logical conclusion.",
  "I am the letter \"A\" among the alphabets, and the dual among the compounds. I am indeed inexhaustible time, and I am the Creator facing in all directions.",
  "I am Death, who takes away everything, and I am also the source of future creations. Among feminine qualities, I am fame, speech, memory, intelligence, steadfastness, and forgiveness.",
  "I am the Brihat Sama among the Sama mantras, and Gayatri among the meters, Among months, I am Margashirsha, and among seasons, I am the flower-bearing spring.",
  "I am the gambling of the deceitful; I am the splendor of the splendid. Among things that conquer, I am victory; I am the determination of the resolute.",
  "I am Vasudeva among the Vrishnis, and Dhananjaya among the Pandavas. Among the sages I am Vyasa, and among poets I am Usana.",
  "I am the punishment of the lawbreakers, and the victory of the victorious. I am the silence of secrets, and the knowledge of the knowledgeable.",
  "O Arjuna, I am the seed of all beings. There is nothing, animate or inanimate, that can exist without me.",
  "There is no end to My divine manifestations, O Arjuna. What I have mentioned is only a sample of My infinite glory.",
  "Whatever is glorious, beautiful, and mighty, know that to be a manifestation of a part of my splendor.",
  "Or what need is there, Arjuna, for all this detailed knowledge? With a single fragment of Myself I pervade and support this entire universe.",
];