List<String> chapter_12_trans_sanskrit = [
  "Arjuna uvācha: evam satatayuktā ye bhaktāstvām paryupāsate, ye cāpyaksaramavyaktam tesām ke yogavittamāh",
  "śrī bhagavān uvācha: mayyāveśya mano ye mām nityayuktā upāsate, śraddhayā parayopetāh te me yuktatamā matāh",
  "ye tavaksaramanirdeśyamavyaktam paryupāsate, sarvatra-gamachintyam cha kūtasthamachalandhruvam",
  "sanniyamyendriyagrāmam sarvatra samabuddhayah, te prāpnuvanti māmeva sarvabhūtahite ratāh",
  "kleśo'dhikatarastesām avyaktāsakta-cetasām, avyaktā hi gatirduhkham dehavadbhiravāpyate",
  "Ye tu sarvāni karmāni mayi sannyasya matparāh ananyenaiva yogena mām dhyāyanta upāsate",
  "Teshaamaham samuddhartaa mrityusamsaarasagarat Bhavaami nachiraat paartha mayyaaveshitachetasam",
  "Mayyeva mana aadhatsva mayi buddhim niveshaya Nivasishyasi mayyeva ata uurdhvam na samshayah",
  "atha cittam samādhātum na śaknosi mayi sthiram abhyāsayogena tato māmicchāptum dhanañjaya",
  "Abhyāse'pyasamartho'si matkarmaparamo bhava Madarthamapi karmāni kurvansiddhimavāpsyasi",
  "Athaitadapyashakto'si kartum madyogamāśritah Sarvakarmaphalatyāgam tatah kuru yatātmavān",
  "Shreyo hi jñānam abhyāsāj jñānād dhyānam viśisyate Dhyānāt karma-phala-tyāgas tyāgāc chāntir anantaram",
  "Advestā sarva-bhūtānām maitrah karuna eva ca Nirmamo nirahankārah sama-duhkha-sukhah ksamī",
  "Santustah satatam yogī yatātmā drdha-niścayah Mayy arpita-mano-buddhir yo mad-bhaktah sa me priyah",
  "Yasmannodvijate loko lokannodvijate cha yaha Harshaamarshabhayodvegair mukto yaha sa cha me priyaha",
  "Anapekshaha shuchirdaksha udaaseeno gatavyathaha Sarvaarambhaparityaagee yo madbhaktaha sa me priyaha",
  "yo na hrsyati na dvesti na śocati na kānksati śubhāśubhaparityāgī bhaktimān yah sa me priyah",
  "samah śatrau ca mitre ca tathā mānāpamānayoh śītosna-sukha-duhkhesu samah sanga-vivarjitah",
  "tulya-nindā-stutir-maunī santusto yena kenacit aniketah sthira-matir-bhaktimān me priyo narah",
  "Ye tu dharmyāmrtamidam yathoktam paryupāsate, śraddadhānā matparamā bhaktāste'tīva me priyāh"
];



List<String> chapter_12_english = [
"Arjuna said: Those devotees who, ever steadfast, worship You with devotion by always speaking of You and meditating upon You, and those who worship the imperishable and the unmanifested—that which is beyond all conception—what is the nature of their devotion?",
  "The Supreme Lord said:Those who fix their minds on Me and always engage in My devotion with steadfast faith, I consider them to be the most perfect in yoga.",
  "But those who worship the imperishable, the indefinable, the unmanifest, the omnipresent, the unthinkable, the unchanging, the immovable and the eternal, they undoubtedly attain Me.",
  "With their senses under control and with a mind that is equal everywhere, such devotees, engaged in the welfare of all beings, surely attain Me.",
  "The sufferings of those who are attached to the unmanifested are greater, for one's attachment to the unmanifested is difficult to overcome. The embodied form is temporary and is the cause of all pain, but the unmanifested is eternal and therefore beyond pain.",
  "But those who dedicate all their actions to Me, regarding Me as the Supreme goal, meditating on Me with single-minded devotion and worshiping Me with exclusive love, I swiftly deliver them from the ocean of birth and death, for their consciousness is united with Me.",
  "For those who have their minds set on Me, I am the swift deliverer from the ocean of birth and death. O Arjuna, for such steadfast devotees of Mine, whose thoughts have merged with Me, I become the swift deliverer from the ocean of birth and death.",
  "Fix your mind on Me alone, engage your intellect in Me; thus you shall surely abide in Me alone hereafter, without a doubt.",
  "But, O Arjuna, you will not be able to steady your mind on Me; for the mind is restless, turbulent, powerful, and obstinate. It is more difficult to control than the wind. However, with practice and detachment, it can be restrained.",
  "If you are unable to practice the regulations of bhakti-yoga, then just try to work for Me, because by working for Me you will come to the perfect stage.",
  "If you are unable to practice the regulations of Bhakti Yoga, then take shelter of My devotion by doing all your work for Me. In that way you shall surely attain Me.",
  "Indeed, knowledge is superior to practice, and meditation surpasses mere knowledge. O Arjuna, the renunciation of the fruits of one's actions is greater than meditation, for peace immediately follows such renunciation.",
  "One who is not envious but is a kind friend to all living entities, who does not think himself a proprietor and is free from false ego, who is equal in both happiness and distress, who is tolerant, always satisfied, self-controlled, and engaged in devotional service with determination, such a devotee of Mine is very dear to Me.",
  "The yogi who is satisfied with the knowledge and the perception gained through meditation, who remains steadfast, who has controlled his senses, and who is devoted to Me, is dear to Me.",
  "Those who neither cause agitation among the people nor become agitated by them, who remain neutral amidst pleasure and pain, who are free from attachment, fear, and anger, are dear to Me.",
  "Those who are impartial, pure, skillful, and undisturbed, who have renounced every undertaking and are devoted to Me, are dear to Me.",
  "One who neither rejoices nor hates, neither grieves nor desires, and who has renounced both good and bad, is dear to Me.",
  "He who is the same to friend and foe, and also in honour and dishonour, who is the same in cold and heat, and in pleasure and pain, who is free from attachment, he is dear to Me.",
  "One who is equal to friends and enemies, who is equipoised in honor and dishonor, heat and cold, pleasure and pain, and who is free from attachment and envy, is dear to Me.",
  "But those who, following this immortal Dharma described above, with faith and regarding Me as the Supreme Goal, worship Me, they are exceedingly dear to Me.",
];