List<String> chapter_three_trans_sanskrit = [
  "Arjuna uvacha: \"Jyayasi chet karmanas te mata buddhir janardana, tat kim karmani ghore mam niyojayasi keshava?\"",
  "Vyamishrena vakyena tvam buddhim mohayasi eva me. Isliye us ek upay ko nishchit karke batao, jisse ki main apne liye shreshth phal prapt kar sakun.",
  "Shri Bhagavan uvacha,\"Loke'smin dwividha nishtha pura prokta mayanagha, Jnana-yogena sankhyanam karma-yogena yoginam.\"",
  "Na karmanam anarambhat naishkarmyam purusho 'shnute la cha sannyasanad eva siddhim samadhigacchati.",
  "Na hi kashchit kshanamapi jatu tishthatyakarmakrit, Karyate hyavashah karma sarvah prakritijair gunaih.",
  "Karmanindriyani samyamya ya aaste manasa smaran, Indriyarthaan vimoodhaatmaa mithyaachaarah sa uchyate.",
  "Yas tvindriyani manasa niyamyaarabhate'rjuna, Karmendriyaih karmayogam asaktah sa vishishyate.",
  "niyatam kuru karma tvam karma jyāyo hyakarmanah, śarīrayātrāpi ca te na prasiddhyedakarmanah",
  "yajñārthāt karmano'nyatra loko'yam karmabandhanah tadartham karma kaunteya mukta-sangah samāchara",
  "sahayajñāh prajāh srstvā purovāca prajāpatih, anena prasavisyadhvam esa vo’stistakāmadhuk ",
  "devān bhāvayatānena te devā bhāvayantu vah parasparam bhāvayantah śreyah param avāpsyatha",
  "istān bhogān hi vo devā dāsyante yajña-bhāvitāh tair dattān apradāyaibhyo yo bhunkte stena eva sah",
  "yajña-śistāśinah santo muchyante sarva-kilbisaih bhujate te tvagham pāpā ye pacantyātma-kāranāt",
  "annād bhavanti bhūtāni parjanyād anna-sambhavah yajñād bhavati parjanyo yajñah karma-samudbhavah",
  "karma brahmodbhavam viddhi brahmāksarasamudbhavam tasmātsarvagatam brahma nityam yajñe pratisthitam",
  "evam pravartitam chakram nanuvartayatiha yah aghayur indriya-ramo mogham partha sa jivati",
  "yastvātmaratireva syādātmatrptaśca mānavah, ātmanyeva ca santustastasya kāryam na vidyate",
  "naiva tasya krtenārtho nākrteneha kaścana, na cāsya sarvabhūtesu kaścidarthavyapāśrayah",
  "tasmādasaktah satatam kāryam karma samāchara, asakto hyācarankarma paramāpnoti pūrusah",
  "karmanaiva hi samsiddhim āsthitā janakādayah, lokasangrahamevāpi sampashyan kartum arhasi",
  "yad yad ācharati śresthas tat tad evetaro janah, sa yat pramānam kurute lokas tad anuvartate",
  "na me pārthāsti kartavyam trisu lokesu kiñcana, nānavāptam avāptavyam varta eva ca karmani",
  "yadi hyaham na varteyam jātu karmanyatandhritah, mama vartmānuvartante manusyāh pārtha sarvaśah",
  "utsīdeyur ime lokā na kuryām karma cedaham, sankarasya ca kartā syām upahanyāmimāh prajāh",
  "saktāh karmanyavidvāmso yathā kurvanti bhārata, kuryādvidvāmstathāsaktaścikīrsurlokasangraham",
  "na buddhi-bhedam janayed ajñānām karma-sanginām, josayet sarva-karmāni vidvān yuktah samācaran.",
  "Prakrteh kriyamānāni gunaih karmāni sarvaśah, ahankāra-vimūdhātmā kartāhamiti manyate",
  "tattvavit tu mahabaho gunakarma-vibhagayoh, gunah guneshu vartante iti matva na sajjate",
  "prakrter guna-sammūdhāh sajjante guna-karmasu tān akrtsna-vido mandān krtsna-vin na vicālayet",
  "mayi sarvāni karmāni sannyasyādhhyātma-cetasā, nirāśīr nirmamo bhūtvā yudhyasva vigata-jvarah",
  "ye me matam idam nityam anutisthanti mānavāh, śraddhāvanto 'nasūyanto muchyante te 'pi karmabhih",
  "ye tvetadabhyasooyanto naanutishthanti me matam, sarvajnaanavimoodhaamstaan viddhi nashtaan achetasah",
  "sadrśaḿ cestate svasyāh prakrter jñānavānapī, prakrtiḿ yānti bhūtāni nigrahah kiḿ karisyati",
  "Indriyasyendriyasyārthe rāga-dvesau vyavasthitau, tayor na vaśam āgacchet tau hy asya paripanthinau",
  "śreyān swadharmo vigunah paradharmāt swanusthitāt, swadharme nidhanam śreyah paradharmo bhayāvahah",
  "arjuna uvāca atha kena prayukto 'yam pāpam carati pūrusah anicchann api vārsneya balād iva niyojitah",
  "śrī-bhagavān uvācha kāma esa krodha esa rajo-guna-samudbhavah mahāśano mahāpāpmā viddhy enam iha vairinam",
  "dhumenāvriyate vahnir yathādarśo malena ca, yatholbenāvrto garbhas tathā tenedamāvrtam",
  "aavrutam jnaanam etena jnaanino nityavairinaa kaama ruupena kaunteya dushpuurenaanalen cha",
  "Indriyani mano buddhirasyadhishthanamucyate, Etairvimohayatyeshah jnanamavrittya dehinam",
  "Tasmāttvamindriyānyādau niyamya bharatarshabha, pāpmānam prajahi hyenam jñānavijñānanāśanam.",
  "indriyāni parāny āhur indriyebhyah param manah manasas tu parā buddhir yo buddheh paratas tu sah",
  "evam buddheh param buddhva samstabhyatmanam atmana jahi shatrum mahabaho kamrupam durasadam",

];

List<String> chapter_three_english = [
  "He Janardana! Yadi tumhari mati ke anusar karma karna jyada uttam mana jata hai toh phir tumhe us durgham karma mein mujhe kyon niyojit kar rahe ho?",
  "By your ambiguous statements, you are confusing my mind. Therefore, state one definite course of action by which I may attain the highest good for myself.",
  "Shri Bhagavan said,\"O sinless one, in this world, there are two kinds of steadfast devotion - that of knowledge and that of action. The steadfast devotion of knowledge is through contemplation (Jnana Yoga), and that of action is through selfless service (Karma Yoga).\"",
  "Without beginning the prescribed duties of life, a person cannot achieve freedom from karma or attain perfection. Similarly, by merely renouncing activities one cannot attain success.",
  "There is no one who can remain without action even for a moment. Indeed, all beings are compelled to act by their qualities born of material nature.",
  "One who controls the senses and the mind, and who is always thoughtful and meditative, is known as a sage with perfect knowledge. However, one who indulges the senses with a deluded mind is known as an imposter and a cheat.",
  "But one who controls the mind, and who is free from attachment and aversion, even while using the senses to engage in actions, attains the supreme perfection of action.",
  "Perform prescribed duty, for action is superior to inaction. Even the maintenance of the body would not be possible for you by inaction.",
  "All actions, other than those done for the purpose of sacrifice, O Arjuna, bind one to this material world. Therefore, perform your prescribed duties without being attached to the fruits of action, for by doing so you will be freed from the bondage of karma.",
  "In ancient times, Prajapati created humans along with sacrificial obligations, saying \"By this, you shall propagate. May this fulfill your wishes.\"",
  "By this offering, you should satisfy the gods, and may the gods satisfy you. Thus nourishing one another, you shall attain to the highest good.",
  "The devas, being satisfied by yajna, will grant you the desired enjoyments. One who enjoys those gifts without offering them back in return is certainly a thief.",
  "The devotees of the Lord are released from all kinds of sins because they eat food which is offered first for sacrifice. Others, who prepare food for personal sense enjoyment, verily eat only sin.",
  "All living beings are born of food. Food is produced from rain. Rain comes from the performance of sacrifice, and sacrifice is generated by the performance of prescribed duties.",
  "Know that all actions come from the Supreme Brahman, who is imperishable and beyond all limits. Therefore, the Supreme is always established in sacrifice.",
  "One who fails to follow the wheel of karma thus set in motion, O Arjuna, lives in vain, delighting only in the senses, indulging in sensual pleasures, and verily such a person lives in delusion.",
  "One who finds pleasure in the Self, and is satisfied with the Self, has no obligation to perform any prescribed duty.",
  "For such a person, there is no need to depend on any external circumstances or material possessions for fulfillment. Nor does such a person have any purpose to fulfill by action or inaction.",
  "Therefore, always perform your duty without being attached to the results. For, by performing duty without attachment, one attains the Supreme.",
  "King Janaka and others attained perfection by performing their prescribed duties. You should also perform your work to set an example for the good of the world.",
  "Whatever action a great man performs, common men follow. And whatever standards he sets by exemplary acts, all the world pursues.",
  "I have nothing to gain in the three worlds, nor do I have any duty to perform. Yet, I am engaged in prescribed duties. For, if I did not engage in work, all these worlds would be doomed.",
  "If I did not perform prescribed duties, O Partha, all men would follow My path. By performing actions in that way, I would be the cause of creating confusion in society.",
  "If I did not perform prescribed duties, these worlds would be devoid of activity. I would be responsible for creating unwanted population, and I would thereby destroy the peace of all living beings.",
  "The ignorant work for their own profit, Arjuna; the wise work for the welfare of the world, without thought for themselves. By abstaining from action, however, even the wise man does not attain freedom from action.",
  "The wise man should not unsettle the minds of the ignorant who are attached to action. He should engage them in all actions, himself fulfilling them with devotion.",
  "The actions (karmas) are performed by the qualities (gunas) of nature (prakrti) entirely. The one with deluded self-identity (ahankāra) thinks \"I am the doer\".",
  "The wise, O mighty-armed Arjuna, do not get attached to the interplay of the three modes of material nature and the corresponding actions. They understand that the modes of nature interact among themselves, and that actions are performed by the modes of nature upon the material body.",
  "Perplexed by the qualities of nature, people get attached to actions. One who understands this truth should not unsettle the ignorant who are attached to actions but should inspire others to act with devotion.",
  "Having surrendered all actions to Me, with a mind focused on the inner self, becoming free from desire and without possessiveness, fight without anxiety.",
  "Those humans who follow this teaching of mine with faith and without envy, they too are freed from the bondage of karma.",
  "But those who criticize this my teaching, and do not follow it, deluded by their own knowledge, they perish, O Arjuna",
  "Even a wise person acts according to their own nature, for all living beings follow their nature. What good can repression do?",
  "Attraction and aversion for the objects of the senses abide in the senses. Let none come under their sway, for they are his adversaries.",
  "It is better to perform one's own duty imperfectly than to master the duty of another. By fulfilling the obligations of one's own dharma, one can attain perfection. But by trying to perform the duties of another, one will only face danger and fear.",
  "Arjuna said: O Varshneya, impelled by what does man commit sin, even unwillingly, as if engaged by force?",
  "The Supreme Lord said: It is desire, it is anger, born of the mode of passion, all-devouring and most sinful. Know this as the enemy here.",
  "Just as a fire is covered by smoke and a mirror is obscured by dust, just as the embryo is covered by the womb, similarly this knowledge is covered by desire.",
  "Knowledge is covered by this constant enemy of the wise, which appears as an insatiable fire in the form of desire, Arjuna.",
  " The senses, mind, and intelligence are said to be the sitting places of this lust. Through them, it clouds the knowledge of the embodied soul and covers the realizations of the true self.",
  "Therefore, O Arjuna, control the senses at the outset and destroy this evil, which obstructs realization of the Truth and knowledge.",
  "The senses are said to be greater than the body, the mind is greater than the senses, the intellect is greater than the mind, and the soul is greater than the intellect.",
  "Having understood the supreme nature of the intellect in this way, by controlling the mind with the Self, O mighty-armed Arjuna, slay the enemy in the form of desire, which is difficult to conquer.",

];