List<String> chapter_nine_trans_sanskrit = [
  "Shri Bhagavaan uvaacha. Idam tu te guhyatamam pravakshyaamyanasooyave. Jnaanam vijnaana sahitam yajjnaatvaa mokshyase'shubhaat.",
  "Rajavidya rajaguhyam pavitramidamuttamam. Pratyakshavagamam dharmyam susukham kartumavyayam.",
  "Ashraddhadhaanaah purushaa dharmasyaasya parantapa, Apraapya maam nivartante mrityusamsaaravartmani.",
  "Maya tatamidam sarvam jagadavyaktamoortinaa, Matsthaani sarvabhootani na chaaham teshvavasthitah.",
  "Na cha matsthaani bhootani pashya me yogamaishwaram, Bhootabhrin na cha bhootastho mamatmaa bhootabhaavana.",
  "Yathaa kaashasthito nityam vaayuh sarvatrago mahan, Tathaa sarvaani bhutaani matsthaaneetyupadhaaraya.",
  "Sarva-bhūtāni kaunteya prakrtim yānti māmikām, kalpa-ksaye punas tāni kalpādau visrjāmy aham.",
  "Prakritim svam avastabhya visrijami punah punah, bhuta-gramamamam krtsnam avasam prakriter vasat.",
  "na cha maam taani karmaani nibadhnanti dhananjaya, udaaseenavadaaseenam asaktam teshu karmasu ",
  "Mayadhkshena prakritih suyate sa-characharam, hetunaneena kaunteya jagadwiparivartate.",
  "Avajananti mam mudha manusim tanum asritam, param bhavam ajananto mama bhuta-maheshvaram.",
  "Moghasha moghakarmano moghajnanaa vichetasah, raakshaseem asureem chaiva prakritim mohineem shritaah.",
  "Mahatmanas tu mam partha daivim prakrtim asritah, bhajantyananya-manaso jnatva bhutadim avyayam.",
  "Satatam kirtayanto mam yatantas ca drdha-vratah, namasyantas ca mam bhaktya nitya-yukta upasate.",
  "Jnana-yajnena capyanye yajanto mam upasate, ekatvena prthaktvena bahudha visvatomukham.",
  "Aham kraturaham yajnah, svadha'hamahamausadham, mantr'o'hamaham evajyam, aham agniraham hutam.",
  "pitāhamasya jagato mātā dhātā pitāmahah vedyam pavitramonkāra rksāma yajureva ca",
  "gatirbhartā prabhuh sāksī nivāsah śaranam suhrt prabhavah pralayah sthānam nidhānam bījamavyayam",
  "tapāmyahamaham varsam nigrhnāmyutsrjāmi ca amrtam caiva mrtyuśca sadasaccāhamarjuna",
  "traividyam mām somapāh pūtapāpā yajñairistvā svargatimi prārthayante te punyamāsādya surendralokam aśnanti divyāndivi devabhogān",
  "te tam bhuktvā svargalokam viśālam ksīne punye martyalokam viśanti evam trayīdharmam anuprapannā gatāgatam kāmakāmā labhante",
  "ananyāś cintayanto mām ye janāh paryupāsate tesām nityābhiyuktānām yoga-ksemam vahāmy aham",
  "ye 'pyanya-devatā bhaktā yajante śraddhayānvitāh te 'pi mām eva kaunteya yajanty avidhi-pūrvakam",
  "aham hi sarva-yajñānām bhoktā cha prabhureva cha na tu mām abhijānanti tattvenātaśh-chyavanti te",
  "yānti deva-vratā devān pitṝn yānti pitr-vratāh bhūtāni yānti bhūtejyā yānti mad-yājino 'pi mām",
  "patram puspam phalam toyam yo me bhaktyā prayacchati tadaham bhaktyupahrtam-aśnāmi prayatātmanah",
  "yat karoshi yad ashnasi yaj juhoshi dadasi yat yat tapasyasi kaunteya tat kurushva madarpanam",
  "śubhāśubhaphalair evam moksyase karmabandhanaih samnyāsa-yoga-yuktātmā vimukto mām upaisyasi",
  "samo'ham sarvabhūtesu na me dvesyo'sti na priyah, ye bhajanti tu mām bhaktyā mayi te tesu cāpyaham",
  "api chet sudurāchāro bhajate māmananyabhāk sādhureva sa mantavyah samyagvyavasito hi sah",
  "Kshipram bhavati dharmatma shashvac-chantim nigachchhati Kaunteya pratijanihi na me bhaktah pranasyati",
  "mām hi pārtha vyapāśritya ye 'pi syuh pāpa-yonayah striyo vaiśyās tathā śūdrās te 'pi yānti parām gatim",
  "kim punar brāhmanāh punyā bhaktā rājarsayas tathā anityam asukham lokam imam prāpya bhajasva mām",
  "manmanā bhava madbhakto madyājī mām namaskuru māmeva isyasi yuktvaivam ātmānam matparāyanah",
];


List<String> chapter_nine_english = [
  "\"Shri Bhagavan said, 'I shall now reveal to you this most secretive knowledge and wisdom, knowing which you shall be liberated from the miseries of material existence. This knowledge is combined with realized experience, and by understanding it, you shall be freed from the cycle of birth and death.'\"",
  "This knowledge is the king of education, the most secret of all secrets. It is the purest knowledge, and because it gives direct perception of the self by realization, it is the perfection of religion. It is everlasting, and it is joyfully performed.",
  "Those who are not faithful in this devotional service cannot attain Me, O conqueror of enemies. Therefore they return to the path of birth and death in this material world.",
  "By Me, in My unmanifested form, this entire universe is pervaded. All beings are in Me, but I am not in them.",
  "And yet everything that is created does not rest in Me. Behold My mystic opulence! Although I am the maintainer of all living entities, and although I am everywhere, still My Self is the very source of creation.",
  "As the mighty wind, blowing everywhere, rests always in the sky, in the same way, all beings rest in Me.",
  "O son of Kunti, all created beings enter into My nature at the end of a cycle of time; and I create them again at the beginning of the next cycle.",
  "By Me, in My unmanifested form, this entire universe is pervaded. All beings are in Me, but I am not in them.",
  "The quote means detachment, or being unattached to the results of one's actions, as Lord Krishna advises Arjuna to perform his duties in the same way.",
  "Under My supervision, nature produces all moving and nonmoving beings. O son of Kunti (Arjuna), for this reason, the material world revolves.",
  "Fools disregard Me, when I take on a human form, not knowing My supreme nature as the great Lord of all beings.",
  "Those with deluded minds, who engage in futile actions, who lack discrimination and who are under the spell of demoniac and atheistic views, are inclined towards demoniac and atheistic forms of nature.",
  "O Arjuna, great souls who have taken refuge in My divine nature worship Me with a single-minded devotion, knowing Me as the immutable source of all beings.",
  "Always singing My glories, striving with great determination, bowing down before Me with devotion, they remain ever steadfast in worshiping Me.",
  "Others worship Me through the sacrifice of knowledge, with the realization that all beings are one in Me and I am in them, while still others worship Me as the universal form, with the various rituals prescribed in the Vedas.",
  "I am the ritual, I am the sacrifice, I am the offering to the ancestors, I am the medicinal herb, I am the mantra, I am the clarified butter, I am the fire, and I am the act of offering.",
  "I am the father, mother, sustainer, and grandsire of this world. The syllable Om, the Rigveda, the Sama Veda, and the Yajur Veda are also Myself and are the purifiers.",
  "This verse describes God as the refuge, support, witness, friend, origin, dissolution, foundation, and eternal seed of all existence.",
  "This is a verse spoken by Lord Krishna in the Bhagavad Gita, where He declares Himself as the controller of the cycle of birth, death, and rebirth, and that He bestows both immortality and death.",
  "This verse from the Bhagavad Gita speaks about the three types of Vedic knowledge (trai-vidya) and how those who follow them and perform Vedic sacrifices attain heaven and enjoy celestial pleasures.",
  "This verse from the Bhagavad Gita explains that those who follow the path of the threefold Vedic knowledge, after enjoying the vast heavenly realm, return to the mortal world when their good deeds are exhausted and thus continue the cycle of birth and death, and those who follow this path fulfill their desires and achieve their goals.",
  "In this verse from the Bhagavad Gita, Lord Krishna says that those who constantly worship and meditate upon Him without any deviation, He personally takes care of their well-being and provides for all their needs.",
  "This verse from the Bhagavad Gita states that even those who worship other deities with faith, they are ultimately worshipping Lord Krishna alone, though they do so without knowledge.",
  "I am the enjoyer and the only Lord of all sacrifices, but those who do not understand My transcendental nature fall down.",
  "Those who worship the celestial gods will go to them, those who worship their ancestors will be reunited with them, and those who worship me will come to me.",
  "Whoever offers to Me with devotion a leaf, a flower, a fruit, or water, I accept that offering from the pure-hearted one with love and devotion.",
  "Whatever you do, whatever you eat, whatever you offer or give away, and whatever austerities you perform - do that as an offering to me.",
  "By this means of renunciation you will be freed from both good and bad results of actions, and equipped with the yoga of renunciation you will be freed and come to Me.",
  "I am equal towards all beings; there is no one hateful or dear to me. But those who worship me with devotion, they abide in me and I also abide in them.",
  "Even if one commits the most abominable actions, if they are devoted to me without deviation, they are to be considered saintly because they have properly resolved. They will quickly become righteous and attain lasting peace.",
  "Quickly he becomes righteous and attains lasting peace. O son of Kunti, know for certain that My devotee never perishes.",
  "O Partha, those who take refuge in Me, even if they are born of sinful wombs, women, vaishyas (merchants), and shudras (servants), can attain the supreme destination",
  "What then of holy men, of royal sages, and of prophets on earth? Having come to this impermanent and joyless world, worship Me.",
  "Always think of Me, become My devotee, worship Me and offer your homage unto Me. Thus you will come to Me without fail. I promise you this because you are My very dear friend."];