List<String> chapter_four_trans_sanskrit = [
  "Imam vivasvate yogam proktavan aham avyayam Vivasvan manave praha manur ikshvakave 'bravit",
  "Evam paramparā-prāptam Imam rājarsayo viduh Sa kāleneha mahatā Yogo nastah parantapa",
  "Sa evāyam mayā te'dya yogah proktah purātanah Bhakto'si me sakhā cheti rahasyam hyetad uttamam",
  "Arjuna uvācha: Aparam bhavato janma, param janma vivasvatah Katham etad vijānīyām tvam ādau proktavān iti.",
  "śrī bhagavān uvāca bahūni me vyatītāni janmāni tava cārjuna tānyaham veda sarvāni na tvam vettha parantapa",
  "ajo 'pi sann avyayātmā bhūtānām īśvaro 'pi san prakrtim svāmadhisthāya sambhavāmy ātma-māyayā",
  "yadā yadā hi dharmasya glānir bhavati bhārata abhyutthānam adharmasya tadātmānam srjāmy aham",
  "paritrānāya sādhūnām vināśāya ca duskrtām dharma-samsthāpanārthāya sambhavāmi yuge yuge",
  "janma karma ca me divyam evam yo vetti tattvatah tyaktvā deham punar janma naiti mām eti so 'rjuna",
  "vīta-rāga-bhaya-krodhā man-mayā mām upāśritāh bahavo jñāna-tapasā pūtā mad-bhāvam āgatāh",
  "ye yathā mām prapadyante tāms tathaiva bhajāmyaham mama vartmānuvartante manusyāh pārtha sarvaśah",
  "kānksantah karmanām siddhim yajanta iha devatāh ksipram hi mānuse loke siddhir bhavati karmajā",
  "chaturvarnyam maya srstam guna-karma-vibhagashah tasya kartaram api mam viddhy akartaram avyayam",
  "na mām karmāni limpanti na me karmaphale sprhā iti mām yo 'bhijānāti karmabhir na sa badhyate",
  "evam jñātvā krtam karma pūrvair api mumuksubhih kuru karmaiva tasmāttvam pūrvaih pūrvataram krtam",
  "Kim karma kim akarmeti kavayo'pyatra mohitāh, Tatte karma pravakshyāmi yaj jnātvā mokshyase 'śubhāt",
  "Karmano hyapi boddhavyam boddhavyam cha vikarmanah. Akarmanashcha boddhavyam gahana karmano gatih",
  "Karmanyakarma yah paśyed akarmani ca karma yah sa buddhimān manusyesu sa yuktah krtsnakarma-krt",
  "Yasya sarve samārambhāh kāma-sankalpa-varjitāh Jñānāgni-dagdha-karmānam tamāhuh panditam budhāh.",
  "tyaktvā karma-phalāsangam nitya-trpto nirāśrayah karmany-abhipravrtto’pi naiva kiñcit karoti sah",
  "nirāśīr yata-cittātmā tyakta-sarva-parigrahah śāriram kevalam karma kurvannāpnoti kilbisam",
  "yadrcchā-lābha-santusto dvandvātīto vimatsarah samah siddhāvasiddhau cha krtvāpi na nibadhyate",
  "gatasangasya muktasya jnanavasthitachetasah, yajnayacaratah karma samagram praviliyate",
  "Brahmārpanam Brahma havirbrahmāgnau Brahmanā hutam Brahmaiva tena gantavyam Brahmakarmasamādhinā",
  "daivamevapare yajñam yoginah paryupāsate, brahmāgnāvapare yajñam yajñenaivopajuhvati",
  "Shrotradini indriyani anye samyama agnishu juhvati. Shabdadi visayan anya indriyagnishu juhvati.",
  "Sarvani indriya-karmani prana-karmani capare. Atma-samyama-yogagnau juhvati jnana-dipite.",
  "Dravya-yajñās tapo-yajñā yogayajñās tathāpare. Svādhyāya-jñāna-yajñāś ca yatayah samshita-vratāh.",
  "Apane juhvati prānaḿ prāne-'panaḿ tathāpare. Prānāpana-gatī ruddhvā prānāyāma-parāyanāh.",
  "Apare niyatahārāh prānān prānesu juhvati. Sarve-'py ete yajña-vido yajña-ksapita-kalmasāh.",
  "Yajñashishtāmritabhujo yānti brahma sanātanam. Nāyam loko 'styayajñasya kuto 'nyah kurusattama.",
  "Evam bahuvidhaa yajnaa vitataa brahmano mukhe. Karmajaan viddhi taan sarvaan evam jnaatvaa vimokshyase.",
  "Shreyan dravyamayad yajnaj jnanayajnah parantapa. Sarvam karmakhilam Partha jnane parisamapyate.",
  "Tadviddhi pranipatena pariprashnena sevaya Upadekshyanti te jnanam jnaninas tattvadarshinah",
  "yaj jñātvā na punar moham evam yāsyasi pāndava yena bhūtāny aśesena draksyasy ātmany atho mayi",
  "api ched asi papebhyah sarvebhyah papa-krittamah sarvam jnana-plavenaiva vrjinam santarishyasi",
  "yathaidhamsi samiddho 'gnir bhasmasāt kurute 'rjuna jñānāgnih sarva-karmāni bhasmasāt kurute tathā",
  "na hi jñānen sadrśam pavitramiha vidyate tat svayam yoga-samsiddhah kālena ātmani vindati",
  "shradhavān labhate jñānam tat-parah samyatendriyah jñānam labdhvā parām śāntim acirenādhigacchati",
  "ajnashchaashraddhadaanashcha samshayaatmaa vinashyati, naayam loko'sti na paro na sukham samshayaatmanah.",
  "yoga-sannyasta-karmaanam jnaana-sanchinna-samshayam aatmavantam na karmaani nibadhnanti dhananjaya",
  "tasmād ajñāna-sambhūtam hrt-stham jñānāsinātmanah, chittvainam samśayam yogam ātishto ttistha bhārata."
];

List<String> chapter_four_english = [
  "The Supreme Lord said: I taught this imperishable yoga to the sun-god, Vivasvan, and Vivasvan instructed it to Manu, the father of mankind, and Manu in turn instructed it to Ikshvaku. This is the famous verse from the Bhagavad Gita where Lord Krishna describes the lineage of the ancient teachings of yoga.",
  "The verse explains that the science of yoga was once well-understood and passed down through a lineage of saintly kings, but as time passed, the chain of succession was broken, and the knowledge of yoga was lost.",
  "Lord Krishna tells Arjuna that he is revealing the ancient knowledge of yoga to him because they have a close relationship and the knowledge was lost over time.",
  "Your birth is recent, while the birth of Vivasvan, the sun-god, is ancient. How am I to understand that you instructed him in the beginning?",
  "The Blessed Lord said: Many, many births both you and I have passed. I can remember all of them, but you cannot, O subduer of the enemy!",
  "Although I am unborn and My transcendental body never deteriorates, and although I am the Lord of all beings, I still appear in every millennium in My original transcendental form, by My own internal potency.",
  "Whenever and wherever there is a decline in religious practice, O Arjuna, and a predominant rise of irreligion—at that time I descend Myself.",
  "For the deliverance of the pious and the destruction of the miscreants, as well as for the establishment of religious principles, I advent Myself in every millennium.",
  "One who understands the divine nature of My birth and activities, O Arjuna, upon leaving the body, attains Me and does not take birth again in this material world.",
  "Being freed from attachment, fear, and anger, being fully absorbed in Me and taking refuge in Me, purified by the austerity of knowledge, many have attained My Being.",
  "As they surrender unto Me, I reward them accordingly. Everyone follows My path in all respects, O son of Pritha.",
  "People desiring success in their actions worship the celestial gods here. For success in action quickly arises in this human world through actions born of nature.",
  "The four categories of occupation were created by Me according to people’s natures and activities. Although I am the creator of this system, know Me to be the non-doer and eternal.",
  "Actions do not cling to me, nor do I desire their fruits. One who knows me in this way is never entangled by action.",
  "Having understood this (the nature of karma and its effects), even those who seek liberation (moksha) have performed action before. Therefore, you too perform your duty (karma) established by tradition, as did the ancients.",
  "Even the wise are confused about what is action and what is inaction. I shall explain to you what action is, knowing which you shall be liberated from the bondage of karma. ",
  "One must understand the nature of work, the nature of forbidden work, and also the nature of inaction. The path of work is mysterious.",
  "He who sees inaction in action, and action in inaction, he is intelligent among men, and he is in the transcendental position, although engaged in all sorts of activities.",
  "Those who have given up all desires and have become free from all sense of proprietorship and false ego, and whose actions have been burnt up by the fire of perfect knowledge—such sages are called learned and wise.",
  "Abandoning attachment to the fruits of actions, always content, and without dependence, even though engaged in action, one does nothing at all.",
  "One who is without desire, with a pure mind, free from all attachment and egoism, and performs actions only with the body, is not tainted by sin even while performing actions.",
  "One who is satisfied with what comes of its own accord, who is free from dualities and envy, and who is equal in success and failure, though engaged in actions, is not bound by them.",
  "For the one who is free from attachment and whose mind is established in knowledge, performing actions as an offering to the Divine, the entire act of work is dissolved.",
  "The act of offering is Brahman, the oblation is Brahman, offered by Brahman in the fire of Brahman. Brahman alone is to be reached by him who is firmly established in Brahman through the performance of actions.",
  "Some yogis worship the gods with sacrifices, while others offer the self as sacrifice by the fire of the Brahman through yoga.",
  "Others offer the functioning senses such as the hearing to the control of the fiery discipline; others offer sound and different objects of the senses into the fire of the control of the senses.",
  "Others offer all senses and their functions, as well as their life force, into the fire of the discipline of self-restraint kindled by knowledge.",
  "Some perform sacrifice of material possessions, others sacrifice through severe penance or yoga, and still others sacrifice through the study and teaching of the scriptures, while practicing strict vows of self-restraint.",
  "Others offer the outgoing breath into the incoming breath and the incoming breath into the outgoing breath, while some are regulated in their breathing and practice breath control, with the goal of focusing the mind.",
  "Others regulate their diet and offer the outgoing breath into the incoming breath and the incoming breath into the outgoing breath, thus remaining always in trance, and with a clear understanding of the principles of sacrifice, they attain liberation from all karmic reactions.",
  "Those who partake of the remnants of the sacrifice attain to the eternal Brahman. This world is not for the one who does not perform sacrifice; how then can they attain liberation?",
  "Various types of sacrifices are spread out before the mouth of Brahman. Know them all as born of action, and knowing thus, you will be liberated.",
  "O Arjuna, the sacrifice of knowledge is superior to the sacrifice of material possessions. All actions in their entirety culminate in knowledge.",
  "Just try to learn the truth by approaching a spiritual master. Inquire from him submissively and render service unto him. The self-realized souls can impart knowledge unto you because they have seen the truth.",
  "Having known this, you will not again fall into delusion, Arjuna. By this you will see all creatures in yourself and also in me.",
  "Even if you are the most sinful of sinners, you shall cross over all sin by the raft of knowledge alone.",
  "As the blazing fire turns firewood to ashes, O Arjuna, so does the fire of knowledge burn to ashes all reactions to material activities.",
  "In this world, there is nothing so sublime and pure as transcendental knowledge. Such knowledge is the mature fruit of all mysticism. And one who has achieved this enjoys the self within himself in due course of time.",
  "With faith, and with senses subdued, gaining knowledge, the steadfast one, having gained supreme peace, soon attains the everlasting Spirit.",
  "Those who are ignorant, faithless and doubtful of the teachings are doomed to perish. For the doubting self, there is neither this world nor the next nor happiness.",
  "O Dhananjaya (Arjuna), for those who have renounced attachment to the fruits of actions, who are of deep knowledge and who are endowed with the resolve of the self, their actions are not bound.",
  "Therefore, with the sword of knowledge, cut asunder the doubts which have arisen in your heart. O Bharata, take refuge in yoga and stand up to fight.",

];