List<String> chapter_15_trans_sanskrit = [
  "śrī-bhagavān uvāca ūrdhva-mūla-madhah-śākham aśvattham prāhur avyayam chandāmsi yasya parnāni yas tam veda sa veda-vit",
  "Adhash cordhvam prasritas tasya shakha Gunapravriddha vishayapravalah Adhash ca mulany anusantatani Karmanubandhini manushya-loke",
  "na rūpam asyeha tathopalabhyate nānto na cādir na ca sampratisthā aśvattham enam suvirūdha-mūlam asanga-śastrena drdhena chhittvā",
  "tatah padam tatparimargitavyam yasmingata na nivartanti bhuyah tameva chaadyam purusham prapadye yatah pravrittih prasrita purani",
  "nirmānamohā jita-sanga-dosā adhyātma-nityā vinivrtta-kāmāh dvandvair vimuktāh sukha-duhkha-samjñair gacchanty amūdhāh padam avyayam tat",
  "na tad bhāsayate sūryo na śaśānko na pāvakah yad gatvā na nivartante tad dhāma paramam mama",
  "Mamaivāmśo jīvaloke jīva-bhūtah sanātanah Manah-sasthānīndriyāni prakrti-sthāni karsati.",
  "Shariram yadavaapnoti yachchaapyutkraamateeshwarah Griheetwaitaani samyaati vaayurgandhaanivaashayat.",
  "Shrotram chakshuhu sparshanam cha rasanam ghranam eva cha Adhisthaya manashchayam vishayanupasevate",
  "Utkramantam sthitam vaapi bhunjaanam vaa gunaanvitam Vimoodhaa naanupashyanti pashyanti jnaanachakshushah",
  "yatanto yoginashchainam pashyantyātmanyavasthitam yatanto 'pyakritātmāno nainam pashyantyachetasah",
  "yadādityagatam tejo jagadbhāsayate'khilam yaccandramasi yaccāgnau tattejo viddhi māmakam",
  "gām āviśya ca bhūtāni dhārayāmy aham ojasā pusnāmi causadhīh sarvāh somo bhūtvā rasātmakah",
  "Aham vaiśvānaro bhūtvā prāninām dehamāśritah Prānāpāna-samāyuktah pacāmyannam caturvidham",
  "sarvasya cāham hrdi sannivisto mattah smrtir jñānam apohanañca, vedaiś ca sarvair aham eva vedyo, vedānta-krd vedavid eva cāham",
  "dvāv imau purusau loke ksaraś cāksara eva ca ksarah sarvāni bhūtāni kūtastho 'ksara ucyate",
  "uttamah purusas tvanyah paramātmetyudāhrtah yo lokatrayam āviśya bibhartyavyaya īśvarah",
  "yasmāt ksaram atīto'ham aksarād api cottamah ato'smi loke vede ca prathitah purusottamah",
  "Yo mām evam asammūdho jānāti purusottamam Sa sarva-vid bhajati mām sarva-bhāvena bhārata.",
  "Iti guhyatamam shastram idamuktam mayaanagha Etadbuddhwaa buddhimaan syaat kritakrityashcha bhaarata",
  ];

List<String> chapter_15_english = [
  "The Supreme Personality of Godhead said: It is said that there is an imperishable banyan tree that has its roots upward and its branches down and whose leaves are the Vedic hymns. One who knows this tree is the knower of the Vedas.",
  "The branches of this world tree extend downwards and upwards, nourished by the three modes of material nature, and its roots are firmly grounded in action. The fruit of action is the material world, with its objects of the senses, and the roots of action bind human beings to this world.",
  "The form of this tree cannot be perceived in this world. No one can understand where it ends, where it begins, or where its foundation is. But with determination one must cut down this strongly rooted tree with the weapon of detachment.",
  "One should then seek that goal upon which, having gone, one does not return. And to that supreme primordial personality, from whom all the creation has manifested, one must surrender oneself in devotion.",
  "Free from pride and delusion, victorious over the evil of attachment, dwelling constantly in the Self, their desires having completely turned away, freed from the pairs of opposites known as pleasure and pain, the undeluded reach that eternal goal." ,
  "The sun does not illumine there, nor the moon, nor the fire. That is My supreme abode, reached by the unmanifested path.",
  "Although I am an eternal soul in the world of the living entities, I am attracting the material nature and its six senses including the mind.",
  "When the Lord obtains a body and when He gives it up, as if engaged in inhaling and exhaling, the living entity also accepts and gives up bodies.",
  "The ears, eyes, touch, tongue, and nose perceive the world, but it is the mind that truly experiences and understands these senses. The mind is the seat of these senses and serves the objects.",
  "Even if something is leaving, staying, or being enjoyed and possesses good qualities, foolish people fail to see its true value. Only those with the eye of knowledge can truly see and understand its worth.",
  "The verse means that those who strive and practice yoga can see the self situated within, but those without self-discipline and a focused mind cannot see it, even though they may make an effort to do so.",
  "The radiance of the sun, which illuminates the whole world, and the splendor of the moon and the brilliance of fire are all due to the effulgence of My (Lord Krishna's) energy.",
  "I enter into each planet, and by My energy they stay in orbit. I become the moon and thereby supply the juice of life to all vegetables.",
  "I am the Vaishvanara, present in the bodies of all living beings, associated with the functions of digestion and assimilation. I digest the four kinds of food with the help of the life airs, Prana and Apana, and thus nourish all living beings.",
  "I am seated in the hearts of all beings. From Me are memory, knowledge, as well as their absence. I am indeed the only object to be known by all the Vedas. I am the originator of Vedanta, and the knower of the Vedas am I.",
  "There are two types of living beings in the material world, the destructible and the indestructible. The destructible are all living beings, and the indestructible is the unchanging consciousness that pervades everything and is known as the supreme soul.",
  "But distinct is the Supreme Person who is called the ultimate controller, who sustains the three worlds, and who is imperishable.",
  "Because I am beyond the perishable and am even higher than the imperishable, I am declared in the Vedas and in the world as the highest of all personalities, the Supreme Being.",
  "Lord Krishna is speaking to his friend and devotee, Arjuna, and emphasizing the importance of knowing Him as the Supreme Personality of Godhead. Lord Krishna explains that those who have true knowledge of Him will worship Him with devotion and love.",
  "This is the most confidential teaching, spoken by me, O sinless one. One who understands this will become wise and will have fulfilled his duty, O Arjuna.",
];