List<String> chapter_17_trans_sanskrit = [
  "Arjuna uvāca, ye śāstravidhimutsrjya yajante śraddhayānvitāh tesām nisthā tu kā krsna sattvam āho rajas tamah?",
  "Shri Bhagavaan Uvaacha, trividhaa bhavati shraddhaa dehinaam saa svabhaavajaa saattwikee raajasee chaiva taamasee cheti taam shrunu",
  "sattvānurūpā sarvasya śraddhā bhavati bhārata śraddhāmayo'yam puruso yo yacchraddhah sa eva sah",
  "Yajante sattvika devan yaksharakshamsi rajasah pretan bhuta-ganams chaanye yajante tamasa janah",
  "Ashastravihitam ghoram tapyante ye tapo janah, dambhahankarasamyuktah kamaragabalanvitah.",
  "karsayantah śarīrastham bhūtagrāmam acetasah mām caivāntah śarīrastham tān viddhy āsura niścayān",
  "āhārastvapi sarvasya trividho bhavati priyah, yajñastapastathā dānam tesām bhedamimam śrnu ",
  "āyuh-sattva-balārogya sukha-prīti-vivardhanāh, rasyāh snigdhāh sthirā hrdyā āhārāh sāttvikapriyāh",
  "katvamla-lavanāty-usna tīksna-rūksa-vidāhinah āhārā rājasasyestā duhkha-śokāmaya-pradāh",
  "Yātayāmam gatarasam pūti paryusitam ca yat, Ucchistamapi cāmedhyam bhojanam tāmasapriyam",
  " Aflākānksibhir yajño vidhi-drsto ya ijyate Yastavyam eveti manah samādhāya sa sāttvikah",
  "Abhisandhāya tu phalam dambhārthamapi caiva yat, ijyate bharataśrestha tam yajñam viddhi rājasam",
  "Vidhihīnamasrstānnam mantrahīnamadaksinam, śraddhāvirahitam yajñam tāmasam paricaksate",
  "deva-dvija-guru-prājña-pūjanam śaucam ārjavam brahmacaryam ahimsā ca śārīram tapa ucyate",
  "anudvegakaram vākyam satyam priyahitam ca yat svādhyāyābhyasanam caiva vānmayam tapa ucyate",
  "manah prasādah saumyatvam maunam ātmavinigrahah, bhāva-sanśuddhir ity etat tapo mānasam ucyate",
  "shraddhayā parayā taptam tapas tat trividham naraih aphalākānkshibhir yuktaih sāttvikam parichakshate",
  "satkāramānapūjārtham tapo dambhena caiva yat kriyate tadiha proktam rājasam calamadhruvam",
  "mūdhagrāhenātmano yatpīdayā kriyate tapah, parasyotsādanārtham vā tattāmasamudāhrtam",
  "dātavyamiti yaddānam dīyate'nupakārine deśe kāle cha pātre cha taddānam sāttvikam smrtam",
  "Yattu pratyupakārārtham phalamuddiśya vā punah Dīyate cha pariklishtam taddānam rājasam smrtam.",
  "adeshakāle yad dānam apātrebhyaśca dīyate asatkrtam avajñātam tattāmasam udāhrtam",
  "om tatsaditi nirdeśo brahmanastrividhah smrtah, brāhmanāstena vedāśca yajñāśca vihitāh purā",
  "tasmaadomityudaahrtya yajñadaanatapahkriyaah, pravartante vidhaanoktaaH satataM brahmavaadinam",
  "Tadityanabhisandhaya phalam yajnatapah kriyah, Danakriyashcha vividhah kriyante mokshakankshibhih.",
  "sadbhāve sādhubhāve ca sadityetatprayujyate praśaste karmāni tathā sacchabdah pārtha yujyate",
  "yajñe tapasi dāne ca sthitih saditi cocyate karma caiva tadarthīyam sadityeva abhidhīyate",
  "aśraddhayā hutam dattam tapas-taptam krtam ca yat, asad-ityucyate pārtha na ca tat-pretya no iha",
];


List<String> chapter_17_english = [
"Arjuna said, 'What is the position of those who disregard the principles of scripture but worship with faith? Is it sattva, rajas, or tamas?'",
  "The Supreme Personality of Godhead said: 'According to the modes of nature acquired by the embodied soul, one's faith can be of three kinds - in goodness, in passion, or in ignorance. Now hear about them in detail.'",
  "O Arjuna, everyone's faith conforms to the nature of their mind. Everyone is a person of faith, and whatever one's faith is, one is verily that.",
  "People in the mode of goodness worship the demigods; those in the mode of passion worship the demons and ghosts; those in the mode of ignorance worship ghosts and spirits.",
  "Those people who perform severe austerities, not sanctioned by scriptures, are full of hypocrisy, egoism, and lustful desires.",
  "Those who are devoid of intelligence and engage in tormenting the elements present in the body, and also those who deny Me who dwell within the body – know them to be of demonic nature.",
  "Even the food that is dear to everyone is of three kinds, as are the sacrifices, austerities, and acts of charity. Hear thou the distinction of these.",
  "Foods dear to those in the mode of goodness increase the duration of life, purify one’s existence and give strength, health, happiness and satisfaction. Such foods are juicy, succulent, fatty, wholesome, and pleasing to the heart.",
  "Foods that are bitter, sour, salty, excessively hot, pungent, dry and burning, are dear to those in the mode of passion. Such foods cause pain, distress, and disease.",
  "Food that is stale, tasteless, putrid, rotten, and impure is dear to those in the mode of ignorance.",
  "The sacrifice performed with the knowledge of the duty, without desiring the fruit, and in accordance with the scriptures is considered as in the mode of goodness. The performer who has subdued the mind and senses, and who is fully absorbed in the performance of the sacrifice, is in the mode of goodness.",
  " But that sacrifice which is performed for the sake of reward or ostentation, know that to be in the mode of passion, O Arjuna, best of the Bharatas.",
  "The sacrifice which is devoid of the scriptural injunctions, without proper distribution of food, devoid of chanting of Vedic hymns, devoid of giving charitable gifts and without faith is considered to be in the mode of ignorance.",
  "Worship of gods, brahmanas, gurus, and the wise; cleanliness; straightforwardness; celibacy; nonviolence — these are the austerities of the body, called tapas.",
  "Speech that is not agitating, true, pleasing and beneficial, and the practice of self-study and repetition of sacred texts, all this is called austerity of speech.",
  "Tranquility of mind, amiability, silence, self-control, and purity of thought—these constitute the austerity of the mind.",
  " The threefold austerity practiced by men with utmost devotion and without any desire for reward is declared to be in the mode of goodness (sattvik).",
  "Performing tapas with the aim of gaining respect, adoration, and worship is done with hypocrisy and is of unstable nature, it is known as Rajasic.",
  "That austerity which is performed with foolish stubbornness, self-torture, or for the purpose of injuring others is said to be in the mode of ignorance.",
  "The giving that is done without expectation of return, with no desire for reward or favor in mind, at an appropriate place and time, to a deserving person, is considered as a sattvic (pure) donation.",
  "But the gift which is given with the expectation of a return, or with a desire for reward, or with hesitation or begrudgingly, is said to be Rajasic.",
  "When a gift is given at an inappropriate time or place, or to unworthy recipients, and when it is given without respect or with disregard, it is considered to be in the mode of ignorance.",
  "\"Om Tat Sat\" is a threefold designation of Brahman. The Vedas, the Brahmanas, and the sacrifices were all ordained by Brahman in ancient times.",
  "Therefore, always following the regulations and prescriptions of the Vedas, activities of sacrifice, charity, and austerity are performed by knowledgeable proponents of the Absolute Truth who constantly engage in the glorification of the Supreme Lord. The word “Om” is uttered to indicate such activities.",
  "By focusing on \"Tat,\" the results of the actions of sacrifice, penance, and charity, are performed in various ways by those desiring liberation.",
  "The word 'sat' is used to describe existence, goodness, and also firmness. The word 'sat' is employed in the sense of excellence, too, O Arjuna!",
  "The steadfastness in sacrifice, in spiritual practices, and in giving is also called sat. And action aimed at transcendental realization is also called sat.",
  "Whatever is sacrificed, offered as oblation, given as a gift, performed as penance, whatever is done with faith - whether it is food, sacrifice, austerity, or charity - and whatever action is performed, O Arjuna, without faith, is called asat (unreal or useless). It has no value here or hereafter.",
];