List<String> chapter_five_trans_sanskrit = [
  "Arjuna uvāca: samnyāsam karmanām krsna punar yogam cha śhansasi yach chhreyo etayor ekam tan me brūhi su-niśhchitam",
  "śhrī-bhagavān uvācha: samnyāsah karmayogaśhcha nihśhreyasa-karāvubhau tayos tu karma-sannyāsāt karma-yogo viśhishyate.",
  "jñeyah sa nitya-sannyāsī yo na dveshti na kānkshati nirdwandvo hi mahā-bāho sukham bandhāt pramuchyate.",
  "sānkhya-yogau prithag bālāh pravadanti na panditāh ekam apy āsthitah samyag ubhayor vindate phalam.",
  "yat sānkhyaīh prāpyate sthānam tad yogair api gamyate ekam sānkhyam ca yogam ca yah paśyati sa paśyati.",
  "samnyāsas tu mahā-bāho duhkham āptum ayogatah yoga-yukto munir brahma na cirenādhigacchati.",
  "yoga-yukto viśuddhātmā vijitātmā jitendriyah sarva-bhūtātma-bhūtātmā kurvann api na lipyate.",
  "naiva kiñcit karomīti yukto manyeta tattvavit paśyañ śrnvan sprśan jighrann aśnan gacchan svapamśvasan",
  "Pralapan visrjan grhnan unmishan nimishanapi, Indriyani indriyarthesu vartanta iti dharayan",
  "Brahmanyādhāya karmāni sangam tyaktvā karoti yah, Lipyate na sa pāpena padmapatramivāmbhasā",
  "Kāyena manasā buddhyā kevalair indriyair api, Yoginah karma kurvanti sangam tyaktvātmaśuddhaye",
  "Yuktah karmaphalam tyaktvā śāntimāpnoti naisthikīm, Ayuktah kāmakārena phale saktō nibadhyatē",
  "Sarvakarmāni manasā sannyasyāste sukham vaśhī, Navadvāre pure dehī naiva kurvan na kārayan",
  "Na kartrtvam na karmāni lokasya srjati prabhuh, Na karmaphalasamyogam svabhāvastu pravartate",
  "Nādatte kasyacit pāpam na caiva sukrtam vibhuh, Ajñānenāvrtam jñānam tena muhyanti jantah",
  "Jñānena tu tadajñānam yesām nāshitamātmanah, Tesāmādityavajjñānam prakāśayati tatparam",
  "Tad-buddhayas tad-ātmānas Tannishthās tat-para-āyanāh, Gachchhantyapunar-āvrttim, Jñāna-nirdhūta-kalmasāh",
  "Vidyāvinaya-sampanne brāhmane gavi hastini śuni chaiva śvapāke cha panditāh sama-darśinah",
  "Ihaiva tairjitah sargo yeshaam saamye sthitam manah, Nirdosham hi samam brahma tasmaad brahmani te sthitaah.",
  "na prahrsyet priyam prāpya nodvijet prāpya cāpriyam sthira-buddhir asammūdho brahma-vid brahmani sthitah",
  "bāhya-sparśesv asaktātmā vindatyātmani yat sukham sa brahma-yoga-yuktātmā sukham aksayam aśnute",
  "Ye hi samsparśajā bhogā duhkhayonaya eva te; ādyantavantah kaunteya na teshu ramate budhah.",
  "shaknoteehaiva yah sodhum praakshareeravimokshanaat kaamakrodhodbhavam vegam sa yuktah sa sukhee narah",
  "yo 'ntah-sukho 'ntararamas tatha 'ntar-jyotir eva yah, sa yogi brahma-nirvanam brahma-bhuto 'dhigacchati",
  "labhante brahma-nirvānam rsayah ksīna-kalmasāh chinnadvaiddhā yatātmānah sarva-bhūta-hite ratāh",
  "kāma-krodha-viyuktānām yatīnām yata-cetasām abhitah brahma-nirvānam vartate viditātmanām",
  "sparshan kritva bahirbahyamshcha kshushchaivaantaré bhruvo, pranapanau samau kritva naasabhyantaracharinau",
  "yatendriyamanobuddhir munir mokshaparayanah vigatachhabhayakrodho yah sada mukta eva sah",
  "bhoktāram yajña-tapasām sarva-loka-maheśvaram suhrdam sarva-bhūtānām jñātvā mām śāntim rcchati",
  ];


List<String> chapter_five_english = [
  "Arjuna said: O Krishna, you praise renunciation of actions, and again you recommend the path of yoga. Please tell me decisively which one is better for me.",
  "The Supreme Lord said: Renunciation of actions and the yoga of action both lead to the highest bliss, but between the two, the yoga of action is superior to the renunciation of actions.",
  "He who neither hates nor desires the fruits of his actions is known as a perpetual renouncer. For, O mighty armed Arjuna, he who is free from the dualities (such as pleasure and pain, success and failure, etc.), is easily liberated from the bondage of material existence and achieves supreme happiness.",
  "Children speak of Sankhya (the path of knowledge) and yogis speak of yoga, but the wise know that these paths lead to the same goal. Only those who are established in one or the other path attain the fruit of both.",
  "That which is attained by the Sankhyas (philosophers) is also attained by the Yogis (practitioners of yoga). One who sees that the path of Sankhya and the path of yoga are one, sees the truth.",
  "O mighty-armed Arjuna, renunciation of actions is difficult to attain without the practice of yoga. A sage who is equipped with the practice of yoga quickly attains Brahman (the ultimate reality).",
  "One who is united with yoga, whose mind is pure, whose self is conquered, whose senses are subdued, and who sees the self in every creature, though performing actions, is never entangled.",
  "A person who is established in yoga and knows the truth thinks, \"I do nothing at all,\" when he sees, hears, touches, smells, eats, moves, sleeps, breathes, and talks.",
  "The mind continuously engages with its objects, and the senses remain engaged with their respective sense objects, even while blinking. Knowing this, one should try to restrain the mind.",
  "One who performs actions while dedicating them to Brahman (the Absolute Reality) and giving up attachment, is not affected by sin, just as a lotus leaf remains untouched by water.",
  "The yogis, by using their body, mind, intellect and senses, perform actions without attachment, for the purification of the self.",
  "One who renounces attachment to the fruits of actions attains tranquility of mind, while one who is attached to the fruits of actions is bound by them.",
  "One who renounces all actions mentally and remains content is in control of their happiness. The embodied soul, who neither acts nor causes others to act, resides in the city of nine gates (the body).",
  "The Lord (prabhuh) does not create agency (kartrtvam) or actions (karmāni) for the world. Nor does Nature (svabhāvah) produce the association of actions and their fruits (karmaphalasamyogam).",
  "The omnipotent Lord neither takes on the sins of anyone nor does he accept anyone's virtuous deeds. Due to ignorance, knowledge remains concealed, and thus, people are bewildered by that.",
  "But for those whose ignorance has been destroyed by knowledge of the Self, that knowledge, like the sun, reveals the Supreme.",
  "Those whose intellect is fixed on That, whose Self is That, who are intent on That alone, and who have renounced all else, attain to That which is as immutable as the infinite. Freed from vice and sin, they go to that supreme state.",
  "The wise see with equal vision a learned and gentle brahmana, a cow, an elephant, a dog, and a dog-eater [outcast].",
  "The one whose mind is established in equanimity, has already conquered the cycle of birth and death. For, in Brahman, the supreme reality, there is no blemish. Therefore, they are established in Brahman.",
  "A person with a steady intellect, who is neither elated by desirable outcomes nor troubled by undesirable outcomes, is said to be a sage with perfect knowledge, established in Brahman.",
  "One who is unattached to external sense objects finds happiness in the Atman (the self) within. In the joy of the Atman, one abides in supreme fulfillment.",
  "Verily, those pleasures that arise from contact with the senses are the sources of unhappiness, and have a beginning and an end. The wise do not delight in them.",
  "Whoever can withstand the impulse of lust and anger before the liberation from the body is a yogi, a happy person.",
  "The yogi who is content and finds delight within, and who is illuminated by the inner light of knowledge, attains the state of Brahman, and becomes one with the Absolute.",
  "The sages who have freed themselves from the bondage of Karma and who are free from all impurities attain the state of Brahma-nirvana. Being devoted to the welfare of all beings, they attain supreme bliss.",
  "For the yogis who are free from desire and anger, who have controlled their minds, and who are engaged in the welfare of all living beings, there is no impediment to the attainment of Brahman, the ultimate state of peace and happiness.",
  "Keeping the outside objects away, fixing the gaze between the eyebrows, regulating the in-going and out-going breaths through the nostrils, with equal flow, the yogi, who has controlled the senses, mind and intellect, attains peace and the supreme state of liberation in Brahman.",
  "One who has controlled their senses, mind, and intellect, and is devoted to liberation, free from desire, fear, and anger, is always liberated.",
  "One who knows Me as the ultimate enjoyer of sacrifices and austerities, the supreme Lord of all planets and demigods, and the benefactor and well-wisher of all living entities, attains peace from the pangs of material miseries.",
];