List<String> chapter_two_trans_sanskrit = [
  "Sañjaya uvāca tam tathā krpayāvistam aśrupūrnākuleksanam visīdantam idam vākyam uvāca madhusūdanah",
  "Srī bhagavān uvāca kutas tvā kaśmalam idam visame samupasthitam anārya justam asvargyam akīrti-karam arjuna",
  "Klaibyam mā sma gamah pārtha naitattvayyupapadyate ksudram hrdayadaurbalyam tyaktvottistha parantapa",
  "Arjuna uvacha, katham bhishmam aham sankhye dronam cha madhusudana, ishubhih pratiyotsyami pujarhavarisudana.",
  "Gurun ahatva hi mahānubhāvān śreyo bhoktum bhaiksyam apīha loke hatvārtha-kāmāms tu gurūn ihaiva bhuñjīya bhogān rudhira-pradigdhān",
  "Na caitad vidmah kataran no garīyo yad vā jayem yadi vā no jayeyuh yān eva hatvā na jijīvisāmas te 'vasthitāh pramukhe dhārtarāstrāh",
  "Kārpanya-dosopahata-svabhāvah prcchāmi tvām dharma-sammūdha-cetāh yac chreyah syān niścitam brūhi tan me śisyas te 'ham śādhi mām tvām prapannam",
  "Na hi prapaśyāmi mamāpanudyād yac chokam uchchosanam indriyānām avāpya bhūmāvasapatnam rddham rājyam surānām api cādhipatyam",
  "Sañjaya uvācha evamuktvā hrishīkeśham gudākeśhah prantapa na yotsya iti govindamuktvā tūshnīm babhūva ha",
  "Tam uvācha hrishīkeśhah prahasann iva bhārata senayor ubhayor madhye vishīdantam idam vachah",
  "Srī bhagavān uvāca, aśocyān anvaśocas tvam prajñā-vādāmśca bhāsase, gatāsūnagatāsūmśca nānuśocanti panditāh.",
  "Na tvevāham jātu nāsam na tvam neme janādhipāh, na caiva na bhavisyāmah sarve vayamatah param ",
  "Dehino 'smin yathā dehe kaumāram yauvanam jarā tathā dehāntara-prāptir dhīras tatra na muhyati",
  "Mātrā-sparśās tu kaunteya śītosna-sukha-duhkha-dāh āgamāpāyino 'nityās tāms titiksasva bhārata",
  "Yam hi na vyathayantyete purusham purusharshabha sama-duhkha-sukham dhiram so 'mrtatvaya kalpate",
  "Nāsato vidyate bhāvo nābhāvo vidyate satah, ubhayorapi drsto'ntastvanayostattvadarśibhih",
  "Avināśi tu tadviddhi yena sarvamidam tatam vināśamavyayasyāsya na kaścitkartum arhati",
  "Antavanta ime dehā nityasyoktāh śarīrinah anāśino 'prameyasya tasmād yudhyasva bhārata",
  "Ya enam vetti hantaram yas cainam manyate hatam ubhau tau na vijanito nayam hanti na hanyate",
  "Na jāyate mriyate vā kadāchin nāyam bhūtvā bhavitā vā na bhūyah ajo nityah śhāśhvato ’yam purāno na hanyate hanyamāne śharīre",
  "Vedāvināśinam nityam ya ena majam avyayam, katham sa purusah pārtha kam ghātayati hanti kam?",
  "Vāsāmsi jīrnāni yathā vihāya navāni grhnāti naro 'parāni tathā śarīrāni vihāya jīrnā ny anyāni samyāti navāni dehī",
  "Nainam chindanti shastrani nainam dahati pavakah na chainam kledayantyapo na shoshayati marutah",
  "Acchedyo ’yam adāhyo ’yam akledyo ’śosya eva ca nityah sarva-gatah sthānur acalo ’yam sanātanah",
  "Avyakto'yam achintyo'yam avikaaryo'yam uchyate, tasmaadevam viditvainam naanushochitum arhasi",
  "Atha chainam nityajatam nityam va manyase mritam, tathapi tvam mahabaho naivam shochitum arhasi.",
  "Jātasya hi dhruvo mrtyur dhruvam janma mrtasya ca tasmādaparihārye'rthe na tvam śocitum arhasi",
  "Avyaktādīni bhūtāni vyaktamadhyāni bhārata avyaktanidhanānyeva tatra kā paridevanā",
  "Aścharyavat paśyati kaścid enam āścharyavad vadati tathāiva chānyah āścharyavach chainam anyah śhrinoti śhrutvāpyenam veda na chaiva kaśchit",
  "Dehī nityam avadhyo 'yam dehe sarvasya bhārata tasmāt sarvāni bhūtāni na tvam śocitum arhasi",
  "Swadharmamapi chaavekshya na vikampitum arhasi dharmyaaddhi yuddhaacchreyo’nyat kshatriyasya na vidyate",
  "Yadrcchayā copapannam svargadvāramapāvrtam sukhinah ksatriyāh pārtha labhante yuddhamīdrśam",
  "Atha cet tvam imam dharmyam sangrāmam na karisyasi tatah svadharmam kīrtim ca hitvā pāpam avāpsyasi",
  "Akīrtim cāpi bhūtāni kathayisyanti te 'vyayām sambhāvitasya cākīrtir maranādatiricyate",
  "Bhayād ranād uparatam mansyante tvām mahā-rathāh yesām cha tvam bahumato bhūtvā yāsyasi lāghavam",
  "Avācyavādāmśca bahūnvadisyanti tavāhitāh nindantastava sāmarthyam tato duhkhataram nu kim",
   "Hato vā prāpsyasi svargam jitvā vā bhoksyase mahīm, Tasmāduttistha kaunteya yuddhāya krta-niścayah",
  "Sukha-duhkhe same kritva labhalabhau jayajayau tato yuddhaya yujyasva naivam papam avapsyasi",
  "Esā te 'bhihitā sānkhye buddhir yoge tvimām śrnu, buddhyā yukto yayā pārtha karmabandham prahāsyasi",
  "Nehābhikrama-nāśo 'sti pratyavāyo na vidyate Sv-alpam apy asya dharmasya trāyate mahato bhayāt",
  "Vyavasāyātmikā buddhir ekeha kuru-nandana, bahushākhā hy anantāś ca buddhayo 'vyavasāyinām.",
  "Yāmimām puspitām vācam pravadantyavipaścitah veda-vādaratāh pārtha nānyad astīti vādinah",
  "Kāmātmānah svargaparā janmakarmaphalapradām kriyāviśesabahulām bhogaishvaryagatim prati",
  "Bhogaiśvaryaprasaktānām tayāpahrta-cetasām vyavasāyātmikā buddhih samādhau na vidhīyate",
  "Traigunyavisayā vedā nistraigunyo bhavārjuna nirdvandvo nityasattvastho niryogaksema ātmavān",
  "Yāvān artha udapāne sarvatah samplutodake tāvān sarvesu vedesu brāhmanasya vijānatah",
  "Karmanyevādhikāraste mā phalesu kadāchana mā karmaphalaheturbhūr mā te sango'stvakarmani",
  "Yogasthah kuru karmāni sangam tyaktvā dhanañjaya, siddhyasiddhyoh samo bhūtvā samatvam yoga uchyate.",
  "Dūrena hy-avaram karma buddhi-yogād dhanañjaya buddhau śaranam anviccha krpanāh phala-hetavah",
  "Buddhiyukto jahātīha ubhe sukrtaduskrte tasmādyogāya yujyasva yogah karmasu kauśalam",
  "karmajam buddhiyuktā hi phalam tyaktvā manīsinah janmabandha-vinirmuktāh padam gacchanty anāmayam",
  "Yadā te moha-kalilam buddhir vyatitarisyati tadā gantāsi nirvedam śrotavyasya śrutasya ca",
  "Shruti-vipratipannā te yadā sthāsyati niśchalā samādhāv achalā buddhis tadā yogam avāpsyasi",
  "Arjuna uvāca: sthita-prajñasya kā bhāsā samādhi-sthasya keśava sthita-dhīh kim prabhaseta kim āsīta vrajeta kim",
  "Srī bhagavān uvāca prajahāti yadā kāmān sarvān pārtha manogatān ātmanyevātmanā tustah sthitaprajñastadocyate",
  "Duhkhesvanudvignamanāh sukhesu vigatasprhah vītarāgabhayakrodhah sthitadhīr munirucyate",
  "Yaha sarvatraanabhisnehas tattat praapya shubhaashubham naabhinandati na dweshti tasya prajnaa pratishthitaa.",
  "Yadā samharate cāyam kūrmo'ngānīva sarvaśah, indriyānīndriyārthebhyas tasya prajñā pratisthitā",
  "Vishayā vinivartante nirāhārasya dehinah rasa-varjam raso’pyasya param drshtvā nivartate",
  "Yatato hyapi kaunteya purusasya vipaśchitah, indriyāni pramāthīni haranti prasabham manah",
  "Tāni sarvāni samyamya yukta āsīta matparah vaśe hi yasyendriyāni tasya prajñā pratisthitā",
  "Dhyāyato visayān pumsah sangas tesūpajāyate sangāt sañjāyate kāmah kāmāt krodho 'bhijāyate",
  "Krodhādbhavati sammohah sammohāt smrti-vibhramah, smrti-bhramśād buddhi-nāśo buddhi-nāśāt pranaśyati",
  "Rāga-dvesa-vimuktaih tu visayān indriyaiś caran ātma-vaśyair vidheyātmā prasādam adhigacchati",
  "Prasāde sarva-duhkhānām hānir asyopajāyate prasanna-cetaso hy āśu buddhih paryavatisthate",
  "Naasti buddhirayuktasya na chaayuktasya bhaavanaa Na chaabhaavayatah shaantirashaantasya kutah sukham.",
  "Indriyānām hi caratām yan mano'nuvihīyate, tadasya harati prajñām vāyurnāvamivāmbhasi",
  "tasmaad yasya mahaabaaho nigriheetaani sarvashah indriyaaneendriyaarthebhyas tasya prajnaa pratishthitaa",
  "Yā niśā sarva-bhūtānām tasyām jāgarti sanyamī yasyām jāgrati bhūtāni sā niśā paśyato muneh",
  "Aapuryamaanam achalapratishtham Samudram aapah pravishanti yadvat Tadvat kaamaa yam pravishanti sarve Sa shantim aapnoti na kaama kaami",
  "Vihaaya kaamaanyah sarvaan pumaamshcharati nihsprhah, nirmamo nirahankaarah sa shaantimadhigacchati",
  "Eshaa braahmee sthitih paartha nainaam praapya vimuhyati sthitaasyaam antakaale 'pi brahma-nirvaanam richchhati.",
];


List<String> chapter_two_english = [
   "Sañjaya said: Seeing Arjuna full of compassion, his mind depressed, his eyes full of tears, Madhusudana, Krishna, spoke the following words.",
  "The Supreme Personality of Godhead said: My dear Arjuna, how have these impurities come upon you? They are not at all befitting a man who knows the value of life. They lead not to higher planets but to infamy.",
   "O Partha, it does not befit you to yield to this unmanliness. Give up such petty weakness of heart and arise, O vanquisher of enemies.",
  "Arjuna said, \"O Madhusudana (Krishna), how can I attack Bhishma and Drona with arrows in this battle? They are both worthy of worship. O destroyer of enemies, I will fight them with arrows, which are suitable for their stature.\"",
  "Killing great souls doesn't make one great, nor does gaining the fruits of one's actions lead to happiness. Serving the wise leads to the supreme goal. Enjoy things that lead to happiness and seek knowledge. Killing one's spiritual master, who is their well-wisher, leads to sin and prevents one from enjoying the things that lead to happiness.",
  "We do not know which is better for us: to conquer them or to be conquered by them. Even if we were to win, we would not know how to enjoy the fruits of victory. And even if they were to kill us, we would still not wish to fight them. Therefore, stand up, Arjuna, and prepare to fight.",
  "With my mind clouded by despair and weakness, I ask you to tell me what is truly best for me. Please instruct me in the path of dharma, which will dispel my doubts and bring me sure knowledge. O Krishna, as your disciple, I have taken refuge in you. Please teach me",
  "I see no way to dispel the grief that is drying up my senses, even if I were to gain unrivaled and prosperous sovereignty over the earth and the gods themselves.",
  "Sanjaya said: Having spoken thus to Arjuna, Arjuna, the chastiser of foes, addressed Krishna, \"Govinda, I shall not fight,\" and fell silent.",
  "Krishna, smiling, then spoke these words to the grieving Arjuna in the midst of the two armies.",
  "The Supreme Lord said: \"While speaking learned words, you are mourning for what is not worthy of grief. Those who are wise lament neither for the living nor for the dead.\"",
  "I am not eternal, nor are you, nor are these kings. Neither were we in the past nor shall we be in the future, all of us are temporary beings.",
  "Just as in this body the embodied soul passes into childhood, youth, and old age, so also at death, the soul passes into another body. The wise person is not bewildered by this.",
  "O son of Kunti, the contacts of the senses with the sense objects give rise to fleeting perceptions of happiness and distress, and are the beginnings of pain and pleasure, and one must learn to tolerate them without being disturbed, O Arjuna.",
   "O best among men, that person who is not disturbed by happiness and distress, and is steady in both, is certainly eligible for liberation.",
  "The unreal has no existence, and the real never ceases to be; the reality of both has been perceived by the seers of truth.",
  "Know that which pervades all this to be indestructible. No one is capable of destroying the imperishable.",
  "O Arjuna, these bodies are perishable, but the soul within the body is indestructible, eternal, and boundless. Therefore, fight, O descendent of Bharata.",
   "One who thinks that the soul kills, and one who thinks that the soul is killed, both are ignorant. The soul neither kills, nor is killed.",
  "For the soul there is neither birth nor death at any time. He has not come into being, does not come into being, and will not come into being. He is unborn, eternal, ever-existing and primeval. He is not slain when the body is slain",
  "The soul is indestructible, eternal, and ever-existing. It is not slain when the body is slain. O Partha, how can a person who knows that the soul is indestructible, eternal, and unborn, kill anyone or cause anyone to kill?",
  "Just as a person puts on new garments after discarding the old ones, similarly, the embodied soul (dehi) enters into new bodies, abandoning the old and useless ones.",
  "Weapons do not cut this Self, fire does not burn it, water does not wet it, and wind does not dry it.",
  "This Self is never born, never dies, Never ceases to exist, never comes into being. This Self is birthless, eternal, Undying, and primeval. It is not destroyed when the body is destroyed.",
  "This self is indestructible, unchanging, and is said to be beyond the realm of the senses and the mind. Therefore, knowing this, you should not grieve.",
  "If, however, you think that this one is born constantly or always dies, even then, O mighty-armed, you should not grieve in this manner.",
  "For that which is born, death is certain, and for the dead, birth is certain. Therefore, you should not grieve over the inevitable.",
  "Things are unmanifest before they appear, manifest in the present, and unmanifest again in the future. So why grieve over them?",
  "Some see this Self as amazing, some describe Him as amazing, and some hear of Him as amazing, while others, even after hearing about Him, cannot understand Him at all.",
  "O Arjuna, this embodied self is eternal, indestructible, and limitless. Therefore, you should not grieve for any creature.",
  "Considering your own duty, you should not waver, for there is nothing better for a Kshatriya than a battle that is fought for a just cause.",
  "O Partha, happy are the Kshatriyas to whom such fighting opportunities come unsought, opening for them the doors of the heavenly planets.",
  "If, however, you do not perform your duty of fighting in this warfare, then you will certainly incur sins for neglecting your duties and thus lose your reputation as a warrior.",
  "People will always speak of your dishonor, and for a respectable person, dishonor is worse than death.",
  "The great warriors will think that you have withdrawn from the battle out of fear, and those who once esteemed you highly will then despise you for your timidity.",
  "Those who are afraid or feel inferior to you will speak many unkind words. But what can be more painful than their disrespecting your ability?",
  "Either you will be killed on the battlefield and attain the heavenly planets, or you will conquer and enjoy the earthly kingdom. Therefore, get up with determination and fight.",
  "Treating pleasure and pain, gain and loss, and victory and defeat alike, get ready for the battle. By doing this, you will not incur sin.",
  "This knowledge of the Sankhya and Yoga system has been imparted to you by Me, O Arjuna. By understanding this knowledge, you will be able to rid yourself of the bondage of actions and their results, and become liberated.",
  "In this, there is no loss of effort, nor is there any harm. Even a little progress on this path can protect one from great danger.",
  "Those who are on this path are resolute in purpose, and their aim is one. O beloved child of the Kurus, the intelligence of those who are irresolute is many-branched.",
  "The ignorant speak of knowledge as if it is different from the pursuit of knowledge, but the wise know that knowledge and its pursuit are one and the same.",
  "Those who are obsessed with desire for pleasure and material wealth, and who are attached to the results of their actions, are unable to achieve true spiritual progress. They are focused only on achieving temporary pleasures and material success, and they believe that this will bring them happiness.",
  "For those who are attached to the enjoyment of material opulence and whose minds are bewildered by such things, the resolute determination for devotional service to the Supreme Lord does not take place.",
  "The Vedas deal with the three modes of material nature, O Arjuna. Rise above these modes, be firmly established in transcendental consciousness. Be free from all dualities and from all anxieties for gain and safety, and be established in the Self.",
  "For a person who knows the supreme Brahman, all the Vedas are nothing but water in a pot.",
  "You have the right to work only, but never to its fruits. Let not the fruits of action be your motive, nor let your attachment be to inaction.",
  "O Dhananjaya, do your duty established in yoga, abandoning attachment to success or failure. Such evenness of mind is called yoga.",
  "O Dhanañjaya, far better indeed is knowledge (buddhi) than mere mechanical practice (karma). Far better is meditation than mindless repetition of sacred texts. Be intent on attaining wisdom. By virtue of this wisdom, you will come to live in peace, the supreme state beyond all miseries.",
  "Endowed with wisdom one casts off in this life both good and evil deeds; therefore devote thyself to yoga; yoga is skill in works.",
  "Those who are wise, endowed with the practice of karma yoga, give up attachment to the results of their actions. Being free from the cycle of birth and death, they attain the state beyond all suffering.",
  "When your intellect crosses over the quagmire of delusion, then you will acquire indifference to what has been heard and what is to be heard.",
  "When your intellect crosses over the mire of delusion, then you will attain dispassion with regard to what has been heard and what is yet to be heard. When your intellect, steady and unshakable, remains firmly fixed in Samadhi (deep meditative absorption), then you will attain yoga.",
  "Arjuna said, \"O Kesava, what is the description of him who has steady wisdom, and is merged in the superconscious state? How does such a person speak? How does he sit? How does he walk?\"",
  "The Blessed Lord said: When a man completely relinquishes all desires arising from the mind, and becomes satisfied in the Self alone by the Self, then he is called as the person of steady wisdom.",
  "He who is unperturbed amidst sorrows, and is free from longing for pleasures, and from attachment, fear, and anger, is called a sage of steady wisdom.",
  "One whose mind is not attached to anything, who remains unaffected by both good and bad fortune, who is free from attachment, fear, and anger, is known as a sage of steady wisdom.",
  "When one can withdraw oneself completely from all the sense objects, just as a tortoise withdraws its limbs into its shell, their wisdom is firmly established.",
  "When a person abstains from consuming sense objects, O Arjuna, all desires for sense gratification cease within him, but the taste for them remains. This taste also disappears when he realizes the Supreme",
  "Indeed, O Arjuna, the senses are so turbulent that they can forcibly carry away the mind of even a person who is striving for perfection.",
  "Having restrained them all, one should remain focused on me as the ultimate goal. For one whose senses are under control, the mind is also under control.",
  "While contemplating the objects of the senses, one develops attachment for them, and from attachment, lust develops, and from lust, anger arises.",
  "From anger, delusion arises, and from delusion, bewilderment of memory. When memory is bewildered, intelligence is lost, and when intelligence is lost, one falls down again into the material pool.",
  "But those who are free from attachment and aversion, and can control their senses through the practice of spiritual discipline, attain serenity of mind. Through such self-control, they remain poised and tranquil even amidst external sensory objects.",
  "In the peace of transcendental consciousness, one finds freedom from all suffering. For such a person, a serene and steadfast mind is quickly established in the state of deep concentration.",
  "There is no wisdom in the one who is not established in yoga, nor is there true contemplation in the one who is not established in tranquility. And in the absence of peace, how can there be happiness for anyone?",
  "That which the mind follows, among the wandering senses, drags away its wisdom, as the wind a ship on the waters.",
  "Therefore, O mighty-armed Arjuna, one whose senses are restrained from their objects is certainly of steady intelligence.",
  "What is night for all beings is the time of awakening for the self-controlled; and the time of awakening for all beings is night for the introspective sage.",
  "Like the ocean, which is always filled with water but is ever undisturbed, he who is established in Self-realization is not disturbed by desires for sense gratification. Indeed, such a person remains free even from desires for all sorts of material things; he is peaceful and does not become agitated",
  "He who has given up all desires and moves about without longing, without the sense of mine-ness and egoism, attains peace.",
  "Having obtained this Brahmi state man is not deluded. Being established in this even at the end of life man attains oneness with Brahman (Moksha).",

];