List<String> chapter_16_trans_sanskrit = [
  "śrībhagavānuvāca, abhayam sattvasamśuddhir-jñānayogavyavasthitih, dānam damaśca yajñaśca svādhyāyastapa ārjavam ",
  "ahimsā satyam akrodhas tyāgah śāntir apaiśunam dayā bhūtesv aloluptvam mārdavam hrīr acāpalam",
  "tejah ksamā dhrtih śaucamadroho nātimānitā, bhavanti sampadam daivīmabhi-jātasya bhārata",
  "dambho darpo 'bhimaanashcha krodhah paarushyameva cha, ajnaanam chaabhijaatasya paartha sampadam aasureem",
  "daivī sampad vimoksāya nibandhāyāsurī matā, mā śucah sampadam daivīm abhijāto'si pāndava",
  "dvau bhūta-sargau loke'smin daiva āsura eva ca daivo vistaraśah prokta āsuram pārtha me śrnu",
  "Pravrttim ca nivrttim ca janā na vidurāsurāh Na śaucam nāpi cācāro na satyam tesu vidyate",
  "asatyam apratistham te jagad āhur anīśvaram aparaspara-sambhūtam kim anyat kāma-haitukam",
  "etām drstim avastabhya nastātmāno 'lpa-buddhayah prabhavanty ugra-karmānah ksayāya jagato 'hitāh",
  "kāmam āśritya duspūram dambham ānamadānvitāh mohād grhītvāsadgrāhān pravartante 'śucivratah",
  "chintām-aparimeyām cha pralayāntām-upāśritāh, kāmopabhoga-paramā etāvad-iti niśchitāh",
  "āśā-pāśa-śatair baddhāh kāma-krodha-parāyanāh īhante kāma-bhogārtham anyāyenārtha-samcayān",
  "idam adya mayā labdham imam prāpsyē manōratham idam astīdam api mē bhavisyati punar dhanam",
  "Asau maya hatah shatrur hanishye cha parananapi, Ishvaro'ham aham bhogi siddho'ham balavan sukhi",
  "ādhyo 'bhijanavān asmi ko 'nyo 'sti sadrśo mayā yaksye dāsyāmi modisya ity ajñāna-vimohitāh",
  "aneka-chitta-vibhrāntā moha-jāla-samāvrtāh prasaktāh kāma-bhogesu patanti narake'shuchau",
  "ātmasambhāvitāh stabdhā dhanamānamadānvitāh, yajante nāmayajñais te dambhenaavidhipūrvakam",
  "ahankāram balam darpam kāmam krodham cha sanśhritāh, mamātma-paradeheshu pradvishanto 'bhyasūyakāh",
  "tān aham dvishatah krūrān samsāreshu narādhamān, kshipāmyajasram aśhubhān āsurīshv eva yonishu",
  "āsurīm yonimāpannā mūdhā janmani janmani, māmaprāpyaiva kaunteya tato yāntyadhamam gatim",
  "trividham narakasyedam dvāram nāshanamātmanah, kāmah krodhastathā lobhas tasmādetattrayam tyajet",
  "etairvimuktah kaunteya tamodvāraih tribhirnarah ācharatayātmanah śreyas tato yāti parām gatim",
  "yah śāstravidhimutsrjya vartate kāmakāratah na sa siddhimavāpnoti na sukham na parām gatim",
  "Tasmācchāstram pramānam te kāryākārya-vyavasthitau Jñātvā śāstra-vidhānoktam karma kartum ihārhasi",
  ];

List<String> chapter_16_english = [
"Sri Bhagavan said, 'Fearlessness, purity of heart, steadfastness in Yoga of knowledge, charity, control of senses, performance of sacrifice, study of scriptures, austerity, and straightforwardness are called the natural virtues of human beings.'",
  "Non-violence, truthfulness, non-anger, renunciation, peace, absence of malice, compassion, absence of greed, gentleness, modesty, and lack of fickleness are the ethical values of the world.",
  "Radiance, forgiveness, steadiness, cleanliness, lack of animosity, absence of self-importance-these constitute divine wealth, O Arjuna!",
  "Arrogance, vanity, and pride, anger, harshness, and ignorance - these qualities belong to those of demoniac nature, O Partha.",
  "The divine qualities lead to liberation, while the demoniac qualities result in bondage. Do not worry, O Pandava, for you were born with divine qualities.",
  "There are two types of beings in this world, the divine and the demonic. The divine has been described in detail, O Arjuna; now hear from me about the demonic.",
  "Those who are demoniac do not know what is to be done and what is not to be done. Neither cleanliness nor proper behavior nor truth is found in them.",
  "They say that the world is unreal, without basis, without a God, and without any moral laws. It is created by mutual union, brought about by lust.",
  "Having embraced this view, those of small intelligence who are lost to themselves engage in unbeneficial, horrible actions that destroy the world.",
  "Taking refuge in insatiable desires, full of hypocrisy, pride, and arrogance, holding false views through delusion, they act with impure vows.",
  "Those who are attached to unlimited anxieties and who are prey to the destruction of the world, worship the sense gratification of lusty desires and become unclean-minded, such individuals have firmly decided that this is the ultimate goal of life.",
  "The desires of those who are full of desires and are dedicated to gratifying their senses are endless and they strive to amass wealth by unjust means for their enjoyment. They are bound by hundreds of thousands of desires and are slaves to their passions of lust and anger. They indulge in sense pleasures excessively and are devoid of discrimination and good conduct.",
  "This that has been acquired by me today, I shall attain my desire. If there is no gain, this will remain with me in the future as well.",
  "I have killed this enemy, and I will kill others also. I am the Lord, the enjoyer, happy and perfect, and powerful.",
"I am mighty and wealthy, and I have influential friends; who else is equal to me? I will perform sacrifices and give gifts, and thus rejoice.' In this way, those deluded by ignorance are confused'",
  "Confused by various thoughts, trapped in a maze of delusion, and addicted to the gratification of desires, they fall into a foul hell.",
  "Those who are self-proclaimed and arrogant, with wealth and egoism, perform sacrifices only in name, violating the rules of the scriptures, with ostentation.",
  "Those who are envious and mischievous, who are the lowest among men, are cast by Me into the ocean of material existence, into various demoniac species of life.",
  "Those cruel haters, the lowest of mankind, I will repeatedly cast into the cycles of birth and death, into the wombs of those with demoniac qualities.",
  "Those who are deluded and who have taken rebirth among demoniacal species, O Arjuna, do not attain Me. They take birth in lower and lower species of life.",
  "The three gates leading to hell are lust, anger, and greed. Therefore, one should give these up for the well-being of the soul.",
  "O Arjuna, a person who is liberated from these three gates of darkness (lust, anger and greed) practices what is best for themselves and thus attains the supreme destination.",
  "One who discards the scriptural injunctions and acts according to their own whims, does not attain perfection, happiness, or the supreme destination.",
  "Therefore let the scripture be your authority in determining what should be done and what should not be done. You have been shown the path of action; now you must act in accordance with it.",

];