List<String> chapter_one_trans_sanskrit = [
  "Dhritarashtra uvācha Dharmaksetre kuruksetre samavetā yuyutsavah māmakāh pāndavāś caiva kim akurvata sañjaya",
  "Sanjaya uvacha drishtva tu pandavanikam vyudham duryodhanas tada acharyam upasangamya raja vachanam abravit",
  "Pashyaitam Panduputranam acharya mahatim chamum,vyudham Drupadaputrena tava shishyena dhimata.",
  "Atra shura maheshvasa bhimaarjuna-sama yudhi, yuyudhano viratascha drupadascha maha-ratha.",
  "Drshtaketuśh chekitānah kāśhirājaśh cha vīryavān purujit kuntibhojaśh cha śhaibyah narapungavah",
  "yudhāmanyuśh cha vikrānta uttamaujāśh cha vīryavān saubhadro draupadeyāśh cha sarva eva mahā-rathāh ",
  "asmākam tu viśhishtā ye tān nibodha dvijottama nāyakā mama sainyasya samjñārtham tān bravīmi te",
  "bhavān bhīshmaśh cha karnaśh cha kripaśh cha samitinjayah aśhvatthāmā vikarnaśh cha saumadattis tathāiva cha ",
  "anye cha bahavah śhūrā madarthe tyaktajīvitāh nānā-śhastra-praharanāh sarve yuddha-viśhāradāh ",
  "aparyāptam tad asmākam balam bhīshmābhirakshitam paryāptam tv idam eteshām balam bhīmābhirakshitam ",
  "ayaneshu cha sarveshu yathā-bhāgam avasthitāh bhīshmam evābhirakshantu bhavantah sarva eva hi",
  "Tasya sanjanayanharsham kuruvriddhah pitamahah Simhanadam vinadyocchaih shankham dadhmau pratapavan",
  "Tatah shankhashcha bheryashcha panavanaka gomukhah Sahasaivabhyahanyanta sa shabdastumulo’bhavat",
  "Tatah shvetaih hayair yukte mahati syandane sthitau Madhavah pandavashchaiva divyau shankhau pradadhmatuh",
  "Pancajanyam hrishikesho devadattam dhananjayah Paundram dadhmau mahashankham bhima-karma vrikodarah",
  "Anantavijayam raja kuntiputro yudhishthirah Nakulah sahadevashcha sughosamanipushpkau ",
  "Kāśhyaścha parameshvāsah śhikhandī cha mahārathah Dhrishtadyumno virātaśhcha sātyakishchāparājita",
  "Drupado draupadeyāśhcha sarvaśhah prithivīpathe Saubhadraśhcha mahābāhuh śhankhāndadhmuh prithak prithak ",
  "Sa ghosho dhārtarāshtrānām hridayāni vyadārayat Nabhaśhcha prithivīm chaiva tumulo vyannunādayan",
  "atha vyavasthitān drstvā dhārtarāstrān kapi-dhvajah pravrtte śastra-sampāte dhanur udyamya pāndavah hrsīkeśam tadā vākyam idam āha mahī-pate",
  "Arjuna uvacha: Senayor ubhayor madhye ratham sthapaya me 'chyuta",
  "Yāvat etān nirīkse 'ham yoddhukāmān avasthitān. Kair mayā saha yoddhavyam asmin rana-samudyame",
  "Yotsyamānān avekse 'ham ya ete 'tra samāgatāh. Dhārtarāstrasya durbuddher yuddhe priya-cikīrsavah.",
  "Sañjaya uvācha, evamukto hrsīkeśo gudākeśena bhāratah, senayor ubhayor madhye sthāpayitvā rathottamam",
  "Bhīsmadrone-pramukhatah sarvesām ca mahīksitām, uvāca pārtha paśyaitān samavetān kurūn iti",
  "Tatrāpaśyat sthitān pārthah pitrān atha pitāmahān, ācāryān mātulān bhrātrān putrān pautrān sakhīms tathā",
  "shvaśhurān suhridaśhchaiva senayor ubhayor api tān samīkshya sa kaunteyah sarvān bandhūn avasthitān kripayā parayāvishto vishīdann idam abravīt",
  "Arjuna uvācha: drishtvemam svajanam Krishna yuyutsum samupasthitam.",
  "sīdanti mama gātrāni mukham ca pariśusyatī vepathuś ca śarīre me roma-harsaś ca jāyate",
  "gāndīvam sramsate hastāttvakcaiva paridahyate na ca śaknomyavasthātum bhramatīva ca me manah",
  "Nimittāni cha paśyāmi viparītāni keśava Na cha śreyo ’nupashyāmi hatvā swajanam āhave",
  "na kānkse vijayam krsna na ca rājyam sukhāni ca, kim no rājyena govinda kim bhogair jīvitena vā ",
  "Yesām arthe kānksitam no rājyam bhogāh sukhāni ca Ta ime’vasthitā yuddhe prānāms tyaktvā dhanāni ca",
  "ācāryāh pitarah putrāstathaiva ca pitāmahāh । mātulāh śvaśurāh pautrāh śyālāh sambandhinastathā",
  "etān na hantum icchāmi ghnato 'pi madhusūdana api trailokya-rājyasya hetoh kim nu mahīkrte",
  "nihatya dhārtarāstrān nah kā prītih syājjanaārdana pāpam evāśrayed asmān hatvaitān ātatāyinah",
  "Tasmānnārhā vayam hantum dhārtarāstrānsvabāndhavān, Svajanam hi katham hatvā sukhinah syāma mādhava",
  "yadyapyete na pashyanti lobhopahatachetasah kulakshayakritam dosham mitradrohe cha paatakam",
  "katham na jñeyamasmābhih pāpādasmānnivartitum kulaksayakrtam dosam prapaśyadbhirjanārdana",
  "kula-ksaye pranaśyanti kula-dharmāh sanātanāh dharme naste kulam krtsnam adharmo 'bhibhavaty uta",
  "adharma-abhibhavat-krishna pradushyanti kula-striyah stri-shu dushtasu vārsneya jāyate varna-sankarah",
  "sankaro narakāyaiva kula-ghnānāḿ kulasya ca patanti pitaro hyesāḿ lupta-pindodaka-kriyāh",
  "doshair etaih kula-ghnanam varna-sankara-karakaih utsadyante jati-dharmah kuladharmashcha shashvatah",
  "utsannakula-dharmānām manusyānām janārdana narake niyatam vāso bhavatītyanuśuśruma",
  "aho bata mahat pāpam kartum vyavasitā vayam, yad rājya-sukha-lobhena hantum svajanam udyatāh ",
  "yadi māmaprati-kāram aśastram śastra-pānayah dhārtarāstrā rane hanyus tan me ksemataram bhavet",
  "sanjaya uvaca evamuktvārjunah sankhye rathopastha upāviśat visrjya sa-śaram cāpam śoka-samvigna-mānasah",
];

List<String> chapter_one_english = [
"Dhritarashtra said: O Sanjaya, after my sons and the sons of Pandu assembled in the place of pilgrimage at Kurukshetra, desiring to fight, what did they do?",
"Sanjaya said: O King, after seeing the army of the Pandavas arrayed in battle formation, King Duryodhana approached his teacher Dronacharya and spoke the following words:",
  "O teacher, behold this mighty army of the sons of Pandu, arranged in battle formation by your wise disciple, the son of Drupada.",
  "Here in this army are many heroic bowmen equal in fighting to Bhima and Arjuna: great fighters like Yuyudhana, Virata and Drupada.",
  "There are also great warriors like Dhrishtaketu, Chekitana, the valiant king of Kashi, Purujit, Kuntibhoja, and Shaibya.",
  "There are also the mighty Yudhamanyu, the brave Uttamauja, the son of Subhadra and the sons of Draupadi, all great chariot warriors.",
  "O best of the brahmins, please note those who are the leaders among us in our army. I mention them to you for your information. The leaders of my army are Bhishma, Drona, and Kripa.",
  "Yourself, Bhishma, Karna, and the victorious Kripa, Ashvatthama, Vikarna, and also the son of Somadatta, all these warriors are great chariot fighters.",
  "There are also many other brave warriors who are prepared to lay down their lives for my sake. They are all skilled in the art of warfare and equipped with many kinds of weapons.",
  "Our strength is inadequate when compared to the opposing army led by Bhishma; but our strength is sufficient when protected by Bhima, the courageous one.",
  "All of you, in your respective positions, must protect Bhishma only, with the greatest care.",
  "The grandfather Bhishma, the oldest of the Kuru dynasty, blew his conch shell very loudly, making a sound like the roar of a lion, giving Duryodhana joy.",
  "Then, after that, conch shells, kettledrums, gongs, and horns were all sounded together, and the sound was tumultuous.",
  "Then, Lord Krishna and Arjuna, seated in a great chariot drawn by white horses, blew their divine conch shells, named Panchajanya and Devadatta, respectively.",
  "Lord Krishna, the master of the senses, blew His conch shell named Panchajanya; Arjuna, the great warrior, blew his conch shell named Devadatta; and Bhima, the voracious eater and performer of herculean tasks, blew his mighty conch shell named Paundra.",
  "King Yudhishthira, the son of Kunti, blew his conch shell Anantavijaya, and Nakula and Sahadeva blew the Sughosha and Manipushpaka conch shells, respectively.",
  "Then there appeared King Kasya, Purujit, Kuntibhoja, and Shaibya, the best among men. The great warrior Sikhandi, Dhrishtadyumna, the son of Drupada, and the warrior king Virata and the unconquered Satyaki.",
  "O King of the earth, there were also the mighty Drupada, the sons of Draupadi, and the great archer Abhimanyu, son of Subhadra. They all blew their conch shells separately.",
  "The sound of that tumultuous uproar reverberated through the earth and sky, and it shook the hearts of your sons, O Dhritarashtra.",
  "When he saw the army of the Kauravas arrayed in battle formation, Arjuna, the son of Pandu, took up his bow and prepared to fight. Addressing Lord Krishna, he said the following words.",
  "Arjuna requests Lord Krishna, who is also known as Achyuta, to position his chariot in the middle of the two armies so that he can see the warriors who have gathered there with the intention to fight.",
  "O Achyuta, place my chariot in the midst of the two armies, that I may behold those who stand here desirous of fighting and, on the eve of this battle, let me know with whom I must fight.",
  "I will survey those who have come here to fight, eager to please the evil-minded son of Dhritarashtra in this battle.",
  "Sañjaya said: O King, having spoken thus, Arjuna, the chastiser of enemies, stationed his chariot in the middle of the two armies",
  "Bhishma, Drona, and the other chiefs of the world, O Partha, beholding the sons of Pandu arrayed in order of battle, approached Duryodhana.",
  "There, Arjuna could see, within the midst of the armies of both parties, fathers and grandfathers, teachers, maternal uncles, brothers, sons, grandsons, friends, and also his fathers-in-law and well-wishers",
  "After seeing all of his relatives, friends, and acquaintances present in both armies, Arjuna was overwhelmed with sorrow and despair. He saw his grandfathers, teachers, uncles, brothers, sons, grandsons, and friends, including his father-in-law, and companions. Upon seeing them, Arjuna, filled with compassion, and feeling deeply attached to them, spoke the following words.",
  "Arjuna said: O Krishna, having seen these people who are eager to fight, who have gathered here to engage in battle,",
  "My limbs are failing and my mouth is drying up. My whole body is trembling, and my hair is standing on end.",
  "The Gandiva slips from my hand and my skin burns all over. I am unable to stand still and my mind is whirling.",
  "O Keśava, I see adverse omens, and I do not foresee any good. I do not desire to slay my own kinsmen in battle.",
  "O Krishna, I do not desire victory, nor kingdom, nor pleasures. What use is sovereignty to us, O Govinda? What pleasure would we have, or even life, after killing our own kinsmen?",
  "Those for whose sake we desire sovereignty, pleasures, and happiness, are standing here in battle, having given up their lives and wealth.",
  "Teachers, fathers, sons, grandfathers, maternal uncles, fathers-in-law, grandsons, brothers-in-law, and other relatives, all of them have assembled here.",
  "O Madhusudana, even though they might want to kill me, I am not willing to fight against them, even for the sake of gaining the three worlds, let alone this earthly kingdom.",
  "O Janardana, what pleasure will we derive from killing the sons of Dhritarashtra? Only sin will accrue to us by killing these aggressors.",
  "Therefore, it is not appropriate for us to kill our own kinsmen, the sons of Dhritarashtra. How can we be happy by killing our own relatives, O Madhava?",
  "Although these men, their hearts overtaken by greed, see no fault in killing one's family or quarreling with friends, why should we, with knowledge of the sin, engage in these acts?",
  "How can we, Janardana (Krishna), not know how to refrain from this sin? Seeing the destruction of the family and the commission of sin, how can we not turn away from it?",
  "With the destruction of the dynasty, the eternal family traditions are vanquished, and thus the rest of the family becomes involved in irreligious practices.",
  "When irreligion is prominent in the family, O Krsna, the women of the family become corrupt, and from the degradation of womanhood, O descendant of Vrsni, comes unwanted progeny.",
  "Sankara, the destroyer of the family, causes the ruination of both the family and those who slew its members. These fallen souls are forced to reside in hellish realms and their forefathers suffer as well, deprived of the offerings of rice-balls and water.",
  "By these misdeeds of those who destroy the family tradition and caste system, the traditional family values and the duties of caste are destroyed forever.",
  "O Janardana, we have heard that for those whose family traditions are destroyed, the eternal laws of dharma are lost. And when the dharma is lost, adharma takes over and such a family's members become bound for hellish planets.",
  "Alas, how great is the sin of our attempt to slay our own kinsmen, out of desire for the pleasures of a kingdom.",
  "If the sons of Dhritarashtra, with weapons in hand, were to kill me unresisting and unarmed in battle, it would be more beneficial for me.",
  "Sanjaya said, \"Saying this, Arjuna, with a mind full of grief and confusion, cast aside his bow and arrows, and sat down on the seat of his chariot.\"",

];