List<String> chapter_18_trans_sanskrit = [
  "Arjuna uvācha: samnyāsasya mahā-bāho tattvam icchāmi veditum tyāgasya ca hrsīkeśa pṛthak keśiniśūdana",
  "Shrī Bhagavān uvācha: kāmyānām karmanām nyāsam sannyāsam kavayo viduh sarva-karma-phala-tyāgam prāhus tyāgam vichaksanāh",
  "tyājyam dosa-vad ity eke karma prāhur manīsinah yajña-dāna-tapah-karma na tyājyam iti cāpare",
  "nishchayam śhrinu me tatra tyāge bharata-sattama tyāgo hi purusha-vyāghra trividhah samprakīrtitah",
  "yajñadāna-tapah-karma na tyājyam kāryam eva tat yajño dānam tapaś chaiva pāvanāni manīshinām",
  "etānyapi tu karmāni sangam tyaktvā phalāni cha kartavyānīti me pārtha niśchitam matam uttamam",
  "niyatasya tu sannyāsah karmano nopapadyate mohāt tasya parityāgas tāmasah parikīrtitah",
  "duhkham ityeva yat karma kāya-kleśa-bhayāt tyajet sa krtvā rājasam tyāgam naiva tyāga-phalam labhet",
  "Kāryamityeva yatkarma niyatam kriyate 'rjuna Sangam tyaktvā phalam caiva sa tyāgah sāttviko matah",
  "Na dvestyakushalam karma kushale nānusajjate Tyāgī sattvasamāvisto medhāvī chinnasamśayah",
  "Na hi dehabhrtā śakyam tyaktum karmāny-aśesatah Yas tu karmaphala-tyāgī sa tyāgītyabhidhīyate",
  "Anistam-istam miśram cha trividham karmanah phalam Bhavaty-atyāginām pretya na tu sannyāsinām kvachit",
  "Pañcaitāni mahābāho kāranāni nibodha me Sānkhye krtānte proktāni siddhaye sarvakarmanām",
  "Adhisthānam tathā kartā karanam cha prthagvidham Vividhāśhcha prthak cheshtā daivam chaivātra pañcha",
  "śarīravānmanobhiryat karma prārabhate narah nyāyyam vā viparītam vā pañcaite tasya hetavah",
  "tatraivam sati kartāramātmānam kevalam tu yah paśyatyakrtabuddhitvānna sa paśyati durmatih",
  "yasya nāhankrto bhāvo buddhir-yasya na lipyate hatvā'pi sa imāmllokānna hanti na nibadhyate",
  "jñānam jñeyam parijñātā trividhā karmachodanā karanam karma karteti trividhah karmasangrahah",
  "jñānam karma cha kartā cha tridhaiva gunabhedatah prochyate gunasankhyāne yathāvachchhrnu tānyapi",
  "sarvabhūtesu yenaikam bhāvamavyayamīksate avibhaktam vibhaktesu tajjñānam viddhi sāttvikam",
  "prthaktvena tu yajjñānam nānābhāvān prthagvidhān vetti sarvesu bhūtesu tajjñānam viddhi rājasam",
  "yattu krtsnavadekasminkārye saktamahaitukam atattvārthavadalpam cha tattāmasamudāhrtam",
  "niyatam sangarahitam-arāgadvesatah krtam aphalaprepsunā karma yattat sāttvikamucyate",
  "yattu kāmepsunā karma sāhankārena vā punah kriyate bahulāyāsam tad rājasamudāhrtam",
  "anubandham ksayam himsāmanapeksya cha paurusam mohād ārabhyate karma yattat tāmasamucyate",
  "muktasango'nahamvādī dhrtyutsāhasamanvitah siddhyasiddhyor nirvikārah kartā sāttvika uchyate",
  "rāgī karmaphalaprepsur lubdho himsātmako 'śucih harsaśokānvitah kartā rājasah parikīrtitah",
  "ayuktah prākrtah stabdhah śatho naiskrtiko'lasah visādī dīrghasūtrī cha kartā tāmasa uchyate",
  "buddher bhedam dhrteśh chaiva gunatas trividham śrnu prochyamānam aśesena prthaktvena dhanañjaya",
  "pravrttim cha nivrttim cha kāryākārye bhayābhaye bandham moksham cha yā vetti buddhih sā pārtha sāttvikī",
  "yayā dharmam adharmam cha kāryam chākāryam eva cha ayathāvad prajānāti buddhih sā pārtha rājasī",
  "adharmam dharmam iti yā manyate tamasāvrtā sarvārthān viparītānśh cha buddhih sā pārtha tāmasī",
  "dhrtyā yayā dhārayate manah-prānendriya-kriyāh yogenāvyabhichārinyā dhrtih sā pārtha sāttvikī",
  "yayā tu dharmakāmārthān dhrtyā dhārayate 'rjuna prasangen phalākānkshī dhrtih sā pārtha rājasī",
  "yayā svapnam bhayam śokam visādam madameva cha na vimuñchati durmedhā dhrtih sā pārtha tāmasī",
  "sukham tvidānīm trividham śhrinu me bharatarshabha abhyāsādramate yatra duhkhāntam cha nigachchhati",
  "yattadagre vishamiva parināme'mrtopamam tatsukham sāttvikam proktamātmabuddhiprasādajam",
  "visayendriya samyogād yattadagre'mrtopamam parināme vishamiva tatsukham rājasam smrtam",
  "yadagre chānubandhe cha sukham mohanamātmanah nidrālasyapramādottham tattāmasamudāhrtam",
  "Na tadasti prthivyām vā divi deveshu vā punah, Sattvam prakrtijairmuktam yadebhih syāttribhirgunaih.",
  "Brāhmanakshatriyaviśhām śhūdrānām cha parantapa, Karmāni pravibhaktāni svabhāvaprabhavairgunaih",
  "Shamah damas tapah śaucam ksāntir ārjavam eva cha, Jñānam vijñānam āstikyam brahma-karma svabhāvajam",
  "Shauryam tejo dhritih dāksyam yuddhe chāpyapalāyanam, Dānam īśvara-bhāvaścha kshātram karma svabhāvajam",
  "krsi-gauraksya-vānijyam vaiśya-karma svabhāvajam, paricaryātmakam karma śūdrasyāpi svabhāvajam",
  "sve sve karmanyabhiratah samsiddhim labhate narah, svakarmaniratah siddhim yathā vindati tacchrnu",
  "Yatah pravrittir bhutānām yena sarvam idam tatam, Svakarmanā tamabhyarchya siddhim vindati mānavah.",
  "śreyān svadharmo vigunah paradharmāt svanusthitāt, svabhāvaniyatam karma kurvannāpnoti kilbisam",
  "sahajam karma kaunteya sad oshamapi na tyajet, sarvārambhā hi doshena dhūmenāgnirivāvrtāh",
  "asaktabuddhih sarvatra jitātmā vigatasprhah, naiskarmyasiddhim paramām samnyāsenādhigacchati",
  "siddhim prāpto yathā brahma tathāpnoti nibodha me, samāsenaiva kaunteya nisthā jñānasya yā parā",
  "buddhyā viśuddhayā yukto dhrtyātmānam niyamya cha, śabdādīnvisayānstyaktvā rāgadvesau vyudasya cha",
  "vivikta-sevī laghvāśī yata-vāk-kāya-mānasah, dhyāna-yoga-paro nityam vairāgyam samupāśritah",
  "ahankāram balam darpam kāmam krodham parigraham vimucya nirmamah śānto brahmabhūyāya kalpate ",
  "brahmabhūtah prasannātmā na śocati na kānksati, samah sarvesu bhūtesu madbhaktim labhate parām",
  "bhaktyā mām abhijānāti yāvānyaśhchāsmi tattvatah, tato mām tattvato jñātvā viśhate tadantaram",
  "sarvakarmānyapi sadā kurvāno madvyapāśrayah, matprasādādavāpnoti śāśvatam padamavyayam",
  "cetasā sarvakarmāni mayi sannyasya matparah, buddhiyogamupāśritya macchittah satatam bhava",
  "macchittah sarvadurgāni matprasādāttarishyasi, atha chettvamahankārānna śroshyasi vinankshyasi",
  "yadahankāramāśritya na yotsya iti manyase, mithyaisha vyavasāyaste prakrtistvām niyokshyati",
  "svabhāvajena kaunteya nibaddhah svena karmanā, kartum nechchhasi yanmohāt karishyasyavaśho'pi tat",
  "īśvarah sarvabhūtānām hrddeśhe'rjuna tishthati, bhrāmayansarvabhūtāni yantrārūdhāni māyayā",
  "tameva śaranam gaccha sarvabhāvena bhārata, tatprasādāt parām śāntim sthānam prāpsyasi śāśvatam",
  "iti te jñānamākhyātam guhyād guhyataram mayā, vimrśhyaitad aśheshena yathechchhasi tathā kuru",
  "sarvaguhyatamam bhūyah śhrnu me paramam vachah, ishto'si me dridhamiti tato vakshyāmi te hitam",
  "manmanā bhava madbhakto madyājī mām namaskuru, māmeva eshyasi satyam te pratijāne priyo'si me",
  "sarvadharmān parityajya māmekam śaranam vraja, aham tvā sarvapāpebhyo mokshayishyāmi mā śuchah",
  "idam te nātapaskāya nābhaktāya kadāchana, na chāśhuśhrushave vāchyam na cha mām yo'bhyaśūyati",
  "ya idam paramam guhyam madbhakteshvabhidhāsyati, bhaktim mayi parām krtvā māmeva eshyatyasamśayah",
  "na cha tasmānmanushyeshu kaśhchinme priyakrttamah, bhavitā na cha me tasmādanyah priyataro bhavi",
  "adhyeshyate cha ya imam dharmyam samvādam āvayoh, jñānayajñena tenāham ishtah syām iti me matih",
  "śraddhāvān anasūyaśhcha śhrnuyādapi yo narah, so'pi muktah śhubhām lokān prāpnuyāt punyakarmanām",
  "kacchidetacchrutam pārtha tvayaikāgrena chetasa, kacchidajñānasammohah pranastaste dhanañjaya",
  "Arjuna uvācha: nashto mohah smrtir labdhā tvatprasādān mayāchyuta sthitosmi gata-sandehah karishye vacanam tava",
  "Sanjaya uvācha:ityaham vāsudevasya pārthasya cha mahātmanah samvādam imam aśrausham adbhutam romaharshanam",
  "Vyāsaprasādācchrutavānetadguhyamaham param, Yogam yogēśvarātkrsnātsāksātkathayatah svayam,",
  "Rājan samsmrtya samsmrtya samvādam imam adbhutam, Keśavārjunayoh punyam hrsyāmi cha muhur muhuh",
  "Taccha samsmrtya samsmrtya rūpamatyadbhutam hareh, Vismayo me mahān rājan hrsyāmi cha punah punah",
  "Yatra yogeshvarah krsno yatra pārtho dhanur-dharah, Tatra śrīr vijayo bhūtir dhruvā nītih matir mama",
];

List<String> chapter_18_english = [
"Arjuna said: O mighty-armed one, I wish to understand the principles of renunciation and the nature of the renounced order of life. O Hrishikesha, please explain these to me separately.",
  "The Supreme Lord said: The wise know that giving up actions that are motivated by desire is renunciation, and they call the giving up of the fruits of all actions the renunciation of the results of action.",
  "Some learned men declare that all kinds of work should be given up as faulty, while others say that acts of sacrifice, charity, and penance should not be abandoned.",
  "O best of the Bharatas, now please listen to me and my conclusive words on the matter of renunciation. Renunciation of material desires is certainly the highest renunciation, and it is of threefold nature, as I will now explain.",
  "Acts of sacrifice, charity, and penance should never be abandoned; they must be performed. Indeed, sacrifice, charity, and penance purify even the great souls.",
  "Furthermore, O Arjuna, it is my supreme and conclusive opinion that all actions should be performed without attachment to the results. This is my final and best instruction to you.",
  "However, giving up actions completely out of delusion is not appropriate for one who is seeking perfection. Such renunciation is said to be in the mode of ignorance.",
  "One should give up actions that are motivated by pain alone, and also those that cause physical strain and fear. Renunciation performed in this way is said to be in the mode of passion and is not productive of any real benefit.",
  "O Arjuna, that action which is performed with a sense of duty, without attachment to the results, is considered a sattvic (pure) form of renunciation.",
  "One who does not hate unpleasant work, nor is attached to enjoyable work, such a person is a renunciant (tyāgī), a person of steady intellect (medhāvī), and free from doubts (chinnasamśayah), being situated in the mode of goodness (sattva).",
  "Indeed, it is not possible for one embodied to completely renounce all actions. But those who renounce the fruits of their actions, they are called true renunciants.",
  "The results of actions are of three kinds - unpleasant, pleasant, and mixed. But for those who have renounced, after death, there is no bondage to the results of actions, nor for the renunciants at any time.",
  "O mighty-armed Arjuna, understand from Me these five factors that are the cause of all actions, as described in the Sānkhya philosophy at the end of their analysis, for the attainment of perfection in all endeavors.",
  "The body, the doer, the various senses, the different activities, and the fifth factor, the divine influence—these are the five factors of action.",
  "By the body, speech, and mind, whatever action a person initiates, these five factors are its causes—either in accordance with righteousness or contrary to it.",
  "But the ignorant person, with an untrained mind, fails to perceive the true nature of the self as the sole doer, even though it is so.",
  "One who has no sense of ego, whose intellect is not tainted, even though engaged in killing, such a person neither kills nor is bound by the action of killing in this world.",
  "Knowledge, the object of knowledge, and the knower are the three factors that motivate action. The instruments of action, the action itself, and the doer are the three constituents of action.",
  "Knowledge, action, and the doer are indeed of three types, according to the distinctions of the modes of material nature. Hear about them as they are described according to the divisions of the modes of nature.",
  "Understand that knowledge to be in the mode of goodness (sattvic) by which one sees the undivided, imperishable reality in all beings, even amidst their diverse manifestations.",
  "Know that knowledge to be in the mode of passion (rājasic) by which one sees various existences as separate and distinct. Such knowledge perceives individuality in all beings.",
  "But that which attaches one to a specific action as if it were the entirety, without considering the cause and effect, without considering the truth, and with little understanding—know that to be in the mode of ignorance (tāmasa).",
  "That action which is performed without attachment, without aversion, and without craving for rewards, and which is performed with proper understanding and determination, is declared to be in the mode of goodness (sattvic).",
  "But that action which is performed with selfish desires and egoistic intentions, and with excessive efforts and exertion, is declared to be in the mode of passion (rājasic).",
  "But that action which is undertaken with delusion, disregarding the consequences, without considering the loss, injury, and one's own capability, is declared to be in the mode of ignorance (tāmasa).",
  "The performer who is free from attachment, non-egotistical, firm, enthusiastic, unaffected by success or failure, is declared to be in the mode of goodness (sattvic).",
  "The performer who is attached, desirous of rewards, greedy, engaging in harmful actions, impure, filled with joy and sorrow, is declared to be in the mode of passion (rājasic).",
  "The performer who is devoid of intelligence, unrefined, stubborn, deceitful, lazy, disheartened, and procrastinating, is declared to be in the mode of ignorance (tāmasa).",
  "O Arjuna, listen to the threefold division of intellect, determination, and the modes of nature, as explained in detail and separately.",
  "That understanding which knows what ought to be done and what ought not to be done, what is to be feared and what is not to be feared, what results in bondage and what leads to liberation, that understanding is considered to be in the mode of goodness (sattvic), O Partha.",
  "That understanding by which one perceives right and wrong, what should be done and what should not be done, improperly and without proper knowledge, that understanding is considered to be in the mode of passion (rājasic), O Partha.",
  "That understanding which considers unrighteousness as righteousness and sees everything upside down, that understanding is considered to be in the mode of ignorance (tāmasa), O Partha.",
  "That firmness by which the mind, vital energy, and senses are controlled, and which is unwavering in the practice of yoga, that firmness is considered to be in the mode of goodness (sattvic), O Partha.",
  "But that determination by which one holds onto duty, desire, and wealth with attachment, O Arjuna, seeking rewards, that determination is considered to be in the mode of passion (rājasic).",
  "But that determination by which one holds onto delusion, fear, sorrow, and despair, and indulges in intoxication, O Partha, that determination is considered to be in the mode of ignorance (tāmasic).",
  "Now, O best of the Bharatas, hear from me about the three types of happiness. By which one attains the end of sorrow, that happiness born of practice.",
  "That which appears like poison at first but tastes like nectar in the end, that happiness is considered to be in the mode of goodness (sāttvic). It arises from the purity of one's intellect and brings clarity and tranquility to the self.",
  "That happiness which arises from the contact of the senses with their objects, which appears like nectar at first but turns into poison in the end, that happiness is considered to be in the mode of passion (rājasic).",
  "That happiness which deludes the self in the beginning and in the sequel, which arises from sleep, indolence, and negligence, that happiness is considered to be in the mode of ignorance (tāmasic).",
  "That which does not exist on the earth, in the celestial abode, or among the gods, and which is beyond the three modes of material nature (sattva, rajas, tamas), that pure consciousness which is free from the material modes of nature is not present.",
  "O Parantapa, the actions of Brahmins, Kshatriyas, Vaishyas, and Shudras are divided according to the qualities born of their own nature.",
  "Peacefulness, self-control, austerity, purity, tolerance, honesty, knowledge, wisdom, and religiousness—these are the natural qualities of actions arising from one's own nature.",
  "Valor, power, determination, skill in battle, and the ability to retreat are the qualities of the Kshatriya born of their inherent nature. Generosity and leadership are also their natural duties.",
  "Agriculture, cattle rearing, and trade are the natural occupations of the Vaisyas born of their inherent nature. Service-oriented work is the natural duty of the Shudras as well.",
  "A person attains perfection by being engaged in their prescribed duties. Hear from me how one who is dedicated to their own duty achieves perfection.",
  "By whom all this universe is pervaded through their manifestation, from whom all beings are born, by performing their prescribed duties with devotion, humans attain perfection.",
  "One's own duty performed imperfectly is better than the duty of another well-performed. By performing actions according to one's nature, one does not incur sin.",
  "O Kaunteya (Arjuna), one should not give up their natural duties, even if they are imperfect. All undertakings are covered with some fault, just as fire is covered by smoke.",
  "One who has a detached intellect, self-controlled, and free from desires attains the supreme perfection of renunciation by renouncing the fruits of their actions.",
  "Just as one attains perfection, one realizes the Supreme Brahman. O Kaunteya (Arjuna), now hear from me about that ultimate state of knowledge, which is attained through unwavering devotion.",
  "With a purified intellect, one should engage in self-control, restraining the mind and senses. Giving up attachment and aversion towards objects such as sound, one should cast aside likes and dislikes.",
  "One who seeks solitude, eats in moderation, controls their speech, body, and mind, who is devoted to the practice of meditation, and who embraces detachment consistently, attains true renunciation.",
  "By letting go of ego, power, arrogance, desire, anger, and possessiveness, one becomes free from attachments, peaceful, and attains the state of being merged with Brahman (the ultimate reality).",
  "Being established in Brahman, with a joyful and serene mind, one neither grieves nor desires. Being equipoised towards all beings, one attains the highest devotion to Me (the Supreme).",
  "By devotion, one truly knows Me in essence, who I am and what I am. Having thus known Me in truth, one immediately enters into Me.",
  "Engaging in all actions, yet always taking refuge in Me, one attains eternal and imperishable abode through My grace.",
  "With your mind focused on Me, surrendering all your actions to Me, and having your intellect established in the yoga of knowledge, always keep your thoughts absorbed in Me.",
  "With your mind focused on Me, you will cross over all obstacles by My grace. But if you become egoistic and do not listen, you will perish.",
  "Thinking that you will not fight due to ego, it is a false determination. Your own nature will compel you to engage in the battle.",
  "O Kaunteya (Arjuna), bound by your own nature, you will involuntarily perform the actions that you do not wish to do due to delusion.",
  "The Supreme Lord resides in the hearts of all beings, O Arjuna. By His divine energy, He causes all beings to revolve like mounted on a machine.",
  "Take refuge in Him alone, O Bharata, with your entire being. By His grace, you will attain the supreme, eternal abode and ultimate peace.",
  "Thus, I have revealed to you the knowledge that is more confidential than the confidential. Reflect upon it thoroughly, and then act as you desire.",
  "Listen again to My supreme and most confidential teaching, for you are dear to Me and I will speak for your benefit, as you are firmly devoted to Me.",
  "Engage your mind in Me, be devoted to Me, offer your actions to Me, and bow down to Me. By doing so, you will come to Me alone, I promise, for you are dear to Me.",
  "Abandon all varieties of dharma and simply surrender unto Me. I will liberate you from all sins. Do not fear.",
  "This knowledge should never be imparted to those who are devoid of austerity, not devoted, and never to those who are disrespectful or who criticize Me.",
  "Whoever reveals this supreme secret to My devotees, with the highest devotion for Me, shall undoubtedly come to Me alone.",
  "And among humans, there is none dearer to Me than they, nor shall there ever be one dearer.",
  "And whoever studies this sacred conversation between us, by that person I am worshipped through the sacrifice of knowledge, and I consider them to be dear to Me.",
  "The person who is full of faith and free from malice, even if they listen to this conversation, shall attain liberation and reach the auspicious worlds attained by those who perform virtuous deeds.",
  "O Arjuna, have you listened to this with single-minded attention? Has your ignorance and delusion been dispelled, O Dhanañjaya (Arjuna)?",
  "Arjuna said: Destroyed is my delusion, and through Your grace, O Acyuta (Krishna), I have regained my memory. I am firm and free from doubt. I will act according to Your words.",
  "Sanjaya said: Thus, I heard this wonderful and thrilling conversation between the mighty-minded Arjuna and Lord Krishna, Vasudeva.",
  "By the grace of Vyasa, I have heard this supreme and confidential knowledge directly from Krishna, the master of all mysticism, who personally spoke it to me.",
  "O King, repeatedly remembering and recollecting this extraordinary dialogue between Keshava (Krishna) and Arjuna, I rejoice again and again.",
  "And repeatedly remembering that divine and wondrous form of Lord Hari (Krishna), O King, I am filled with great astonishment and joy, again and again.",
  "Wherever there is Krishna, the Lord of Yoga, and wherever there is Arjuna, the wielder of the bow, there will be prosperity, victory, happiness, and firm determination. Such is my conviction.",
];